//
//  CategoryManager.swift
//  tori
//
//  Created by Fahad Munawar on 5/15/24.
//

import Foundation
import SwiftUI
import SwiftData

enum yelpCategories: String, CaseIterable{
    
    case activeLife = "Active"
    case arts = "Leisure"
    case beauty = "Relax"
    case food = "Food"
    case nightLife = "Night"
    case localFlavor = "Local"
    
    var background: Color {
        switch self {
        default:
                .gray
        }
    }
    
    var icon: String {
        switch self {
        case .activeLife:
            "figure.cooldown"
        case .arts:
            "pencil.and.scribble"
        case .beauty:
            "bubbles.and.sparkles.fill"
        case .food:
            "fork.knife"
        case .nightLife:
            "music.quarternote.3"
        default:
            "figure"
        }
    }
}

@Model
class YelpCategory {
    var name: String
    var subCategories: [SubCategory] = []
    
    init(name: String, subCategories: [SubCategory]) {
        self.name = name
        self.subCategories = subCategories
    }
}

@Model
class SubCategory {
    var title: String
    var alias: String
    var count: Int
    
    init(title: String, alias: String, count: Int = 0) {
        self.title = title
        self.alias = alias
        self.count = count
    }
}

@Model
class CategoryManager: ObservableObject {
    
    var categories: [YelpCategory]
    
    init() {
        categories = [
            YelpCategory(name: "Active", subCategories: [
                SubCategory(title: "Airsoft", alias: "airsoft"),
                SubCategory(title: "Amateur Sports Teams", alias: "amateursportsteams"),
                SubCategory(title: "Amusement Parks", alias: "amusementparks"),
                SubCategory(title: "Aquariums", alias: "aquariums"),
                SubCategory(title: "Archery", alias: "archery"),
                SubCategory(title: "ATV Rentals/Tours", alias: "atvrentalstours"),
                SubCategory(title: "Axe Throwing", alias: "axethrowing"),
                SubCategory(title: "Badminton", alias: "badminton"),
                SubCategory(title: "Baseball Fields", alias: "baseballfields"),
                SubCategory(title: "Basketball Courts", alias: "basketballcourts"),
                SubCategory(title: "Bathing Area", alias: "bathingarea"),
                SubCategory(title: "Batting Cages", alias: "battingcages"),
                SubCategory(title: "Beach Equipment Rentals", alias: "beachequipmentrentals"),
                SubCategory(title: "Beach Volleyball", alias: "beachvolleyball"),
                SubCategory(title: "Beaches", alias: "beaches"),
                SubCategory(title: "Bicycle Paths", alias: "bicyclepaths"),
                SubCategory(title: "Bike Parking", alias: "bikeparking"),
                SubCategory(title: "Bike Rentals", alias: "bikerentals"),
                SubCategory(title: "Boating", alias: "boating"),
                SubCategory(title: "Bobsledding", alias: "bobsledding"),
                SubCategory(title: "Bocce Ball", alias: "bocceball"),
                SubCategory(title: "Bowling", alias: "bowling"),
                SubCategory(title: "Bubble Soccer", alias: "bubblesoccer"),
                SubCategory(title: "Bungee Jumping", alias: "bungeejumping"),
                SubCategory(title: "Canyoneering", alias: "canyoneering"),
                SubCategory(title: "Carousels", alias: "carousels"),
                SubCategory(title: "Challenge Courses", alias: "challengecourses"),
                SubCategory(title: "Climbing", alias: "climbing"),
                SubCategory(title: "Cycling Classes", alias: "cyclingclasses"),
                SubCategory(title: "Dart Arenas", alias: "dartarenas"),
                SubCategory(title: "Disc Golf", alias: "discgolf"),
                SubCategory(title: "Diving", alias: "diving"),
                SubCategory(title: "Free Diving", alias: "freediving"),
                SubCategory(title: "Scuba Diving", alias: "scubadiving"),
                SubCategory(title: "Escape Games", alias: "escapegames"),
                SubCategory(title: "Fencing Clubs", alias: "fencingclubs"),
                SubCategory(title: "Fishing", alias: "fishing"),
                SubCategory(title: "Fitness & Instruction", alias: "fitnessandinstruction"),
                SubCategory(title: "Aerial Fitness", alias: "aerialfitness"),
                SubCategory(title: "Barre Classes", alias: "barreclasses"),
                SubCategory(title: "Boxing", alias: "boxing"),
                SubCategory(title: "Cardio Classes", alias: "cardioclasses"),
                SubCategory(title: "Dance Studios", alias: "dancestudios"),
                SubCategory(title: "Golf Lessons", alias: "golflessons"),
                SubCategory(title: "Gyms", alias: "gyms"),
                SubCategory(title: "Circuit Training Gyms", alias: "circuittraininggyms"),
                SubCategory(title: "Interval Training Gyms", alias: "intervaltraininggyms"),
                SubCategory(title: "Martial Arts", alias: "martialarts"),
                SubCategory(title: "Brazilian Jiu-jitsu", alias: "brazilianjiujitsu"),
                SubCategory(title: "Chinese Martial Arts", alias: "chinesemartialarts"),
                SubCategory(title: "Karate", alias: "karate"),
                SubCategory(title: "Kickboxing", alias: "kickboxing"),
                SubCategory(title: "Muay Thai", alias: "muaythai"),
                SubCategory(title: "Taekwondo", alias: "taekwondo"),
                SubCategory(title: "Meditation Centers", alias: "meditationcenters"),
                SubCategory(title: "Pilates", alias: "pilates"),
                SubCategory(title: "Qi Gong", alias: "qigong"),
                SubCategory(title: "Self-defense Classes", alias: "selfdefenseclasses"),
                SubCategory(title: "Swimming Lessons/Schools", alias: "swimminglessonsschools"),
                SubCategory(title: "Tai Chi", alias: "taichi"),
                SubCategory(title: "Trainers", alias: "trainers"),
                SubCategory(title: "Yoga", alias: "yoga"),
                SubCategory(title: "Flyboarding", alias: "flyboarding"),
                SubCategory(title: "Gliding", alias: "gliding"),
                SubCategory(title: "Go Karts", alias: "gokarts"),
                SubCategory(title: "Golf", alias: "golf"),
                SubCategory(title: "Gun/Rifle Ranges", alias: "gunrifleranges"),
                SubCategory(title: "Gymnastics", alias: "gymnastics"),
                SubCategory(title: "Handball", alias: "handball"),
                SubCategory(title: "Hang Gliding", alias: "hanggliding"),
                SubCategory(title: "Hiking", alias: "hiking"),
                SubCategory(title: "Horse Racing", alias: "horseracing"),
                SubCategory(title: "Horseback Riding", alias: "horsebackriding"),
                SubCategory(title: "Hot Air Balloons", alias: "hotairballoons"),
                SubCategory(title: "Indoor Playcentre", alias: "indoorplaycentre"),
                SubCategory(title: "Jet Skis", alias: "jetskis"),
                SubCategory(title: "Kids Activities", alias: "kidsactivities"),
                SubCategory(title: "Kiteboarding", alias: "kiteboarding"),
                SubCategory(title: "Lakes", alias: "lakes"),
                SubCategory(title: "Laser Tag", alias: "lasertag"),
                SubCategory(title: "Lawn Bowling", alias: "lawnbowling"),
                SubCategory(title: "Mini Golf", alias: "minigolf"),
                SubCategory(title: "Mountain Biking", alias: "mountainbiking"),
                SubCategory(title: "Nudist", alias: "nudist"),
                SubCategory(title: "Paddleboarding", alias: "paddleboarding"),
                SubCategory(title: "Paintball", alias: "paintball"),
                SubCategory(title: "Paragliding", alias: "paragliding"),
                SubCategory(title: "Parasailing", alias: "parasailing"),
                SubCategory(title: "Parks", alias: "parks"),
                SubCategory(title: "Dog Parks", alias: "dogparks"),
                SubCategory(title: "Skate Parks", alias: "skateparks"),
                SubCategory(title: "Pickleball", alias: "pickleball"),
                SubCategory(title: "Playgrounds", alias: "playgrounds"),
                SubCategory(title: "Public Plazas", alias: "publicplazas"),
                SubCategory(title: "Races & Competitions", alias: "racescompetitions"),
                SubCategory(title: "Racing Experience", alias: "racingexperience"),
                SubCategory(title: "Rafting/Kayaking", alias: "raftingkayaking"),
                SubCategory(title: "Recreation Centers", alias: "recreationcenters"),
                SubCategory(title: "Rock Climbing", alias: "rockclimbing"),
                SubCategory(title: "Sailing", alias: "sailing"),
                SubCategory(title: "Scavenger Hunts", alias: "scavengerhunts"),
                SubCategory(title: "Scooter Rentals", alias: "scooterrentals"),
                SubCategory(title: "Senior Centers", alias: "seniorcenters"),
                SubCategory(title: "Skating Rinks", alias: "skatingrinks"),
                SubCategory(title: "Skiing", alias: "skiing"),
                SubCategory(title: "Skydiving", alias: "skydiving"),
                SubCategory(title: "Sledding", alias: "sledding"),
                SubCategory(title: "Snorkeling", alias: "snorkeling"),
                SubCategory(title: "Soccer", alias: "soccer"),
                SubCategory(title: "Sport Equipment Hire", alias: "sportequipmenthire"),
                SubCategory(title: "Sports Clubs", alias: "sportsclubs"),
                SubCategory(title: "Squash", alias: "squash"),
                SubCategory(title: "Summer Camps", alias: "summercamps"),
                SubCategory(title: "Surf Lifesaving", alias: "surflifesaving"),
                SubCategory(title: "Surfing", alias: "surfing"),
                SubCategory(title: "Swimming Pools", alias: "swimmingpools"),
                SubCategory(title: "Tennis", alias: "tennis"),
                SubCategory(title: "Trampoline Parks", alias: "trampolineparks"),
                SubCategory(title: "Tubing", alias: "tubing"),
                SubCategory(title: "Volleyball", alias: "volleyball"),
                SubCategory(title: "Water Parks", alias: "waterparks"),
                SubCategory(title: "Wildlife Hunting Ranges", alias: "wildlifehuntingranges"),
                SubCategory(title: "Ziplining", alias: "ziplining"),
                SubCategory(title: "Zoos", alias: "zoos"),
                SubCategory(title: "Petting Zoos", alias: "pettingzoos"),
                SubCategory(title: "Zorbing", alias: "zorbing")
            ]),
            YelpCategory(name: "Night", subCategories: [
                SubCategory(title: "Adult Entertainment", alias: "adultentertainment"),
                SubCategory(title: "Strip Clubs", alias: "stripclubs"),
                SubCategory(title: "Striptease Dancers", alias: "stripteasedancers"),
                SubCategory(title: "Bar Crawl", alias: "barcrawl"),
                SubCategory(title: "Bars", alias: "bars"),
                SubCategory(title: "Airport Lounges", alias: "airportlounges"),
                SubCategory(title: "Beer Bar", alias: "beerbar"),
                SubCategory(title: "Champagne Bars", alias: "champagnebars"),
                SubCategory(title: "Cigar Bars", alias: "cigarbars"),
                SubCategory(title: "Cocktail Bars", alias: "cocktailbars"),
                SubCategory(title: "Dive Bars", alias: "divebars"),
                SubCategory(title: "Drive-Thru Bars", alias: "drivethrubars"),
                SubCategory(title: "Gay Bars", alias: "gaybars"),
                SubCategory(title: "Hookah Bars", alias: "hookahbars"),
                SubCategory(title: "Irish Pub", alias: "irishpub"),
                SubCategory(title: "Lounges", alias: "lounges"),
                SubCategory(title: "Pubs", alias: "pubs"),
                SubCategory(title: "Speakeasies", alias: "speakeasies"),
                SubCategory(title: "Sports Bars", alias: "sportsbars"),
                SubCategory(title: "Tiki Bars", alias: "tikibars"),
                SubCategory(title: "Vermouth Bars", alias: "vermouthbars"),
                SubCategory(title: "Whiskey Bars", alias: "whiskeybars"),
                SubCategory(title: "Wine Bars", alias: "winebars"),
                SubCategory(title: "Beer Gardens", alias: "beergardens"),
                SubCategory(title: "Club Crawl", alias: "clubcrawl"),
                SubCategory(title: "Comedy Clubs", alias: "comedyclubs"),
                SubCategory(title: "Country Dance Halls", alias: "countrydancehalls"),
                SubCategory(title: "Dance Clubs", alias: "danceclubs"),
                SubCategory(title: "Jazz & Blues", alias: "jazzblues"),
                SubCategory(title: "Karaoke", alias: "karaoke"),
                SubCategory(title: "Music Venues", alias: "musicvenues"),
                SubCategory(title: "Piano Bars", alias: "pianobars"),
                SubCategory(title: "Pool Halls", alias: "poolhalls")
            ]),
            YelpCategory(name: "Food", subCategories: [
                SubCategory(title: "Afghan", alias: "afghan"),
                SubCategory(title: "African", alias: "african"),
                SubCategory(title: "Senegalese", alias: "senegalese"),
                SubCategory(title: "South African", alias: "southafrican"),
                SubCategory(title: "American (New)", alias: "americannew"),
                SubCategory(title: "American (Traditional)", alias: "americantraditional"),
                SubCategory(title: "Andalusian", alias: "andalusian"),
                SubCategory(title: "Arabian", alias: "arabian"),
                SubCategory(title: "Arab Pizza", alias: "arabpizza"),
                SubCategory(title: "Argentine", alias: "argentine"),
                SubCategory(title: "Armenian", alias: "armenian"),
                SubCategory(title: "Asian Fusion", alias: "asianfusion"),
                SubCategory(title: "Asturian", alias: "asturian"),
                SubCategory(title: "Australian", alias: "australian"),
                SubCategory(title: "Austrian", alias: "austrian"),
                SubCategory(title: "Baguettes", alias: "baguettes"),
                SubCategory(title: "Bangladeshi", alias: "bangladeshi"),
                SubCategory(title: "Barbeque", alias: "barbeque"),
                SubCategory(title: "Basque", alias: "basque"),
                SubCategory(title: "Bavarian", alias: "bavarian"),
                SubCategory(title: "Beer Garden", alias: "beergarden"),
                SubCategory(title: "Beer Hall", alias: "beerhall"),
                SubCategory(title: "Beisl", alias: "beisl"),
                SubCategory(title: "Belgian", alias: "belgian"),
                SubCategory(title: "Flemish", alias: "flemish"),
                SubCategory(title: "Bistros", alias: "bistros"),
                SubCategory(title: "Black Sea", alias: "blacksea"),
                SubCategory(title: "Brasseries", alias: "brasseries"),
                SubCategory(title: "Brazilian", alias: "brazilian"),
                SubCategory(title: "Brazilian Empanadas", alias: "brazilianempanadas"),
                SubCategory(title: "Central Brazilian", alias: "centralbrazilian"),
                SubCategory(title: "Northeastern Brazilian", alias: "northeasternbrazilian"),
                SubCategory(title: "Northern Brazilian", alias: "northernbrazilian"),
                SubCategory(title: "Rodizios", alias: "rodizios"),
                SubCategory(title: "Breakfast & Brunch", alias: "breakfastbrunch"),
                SubCategory(title: "Pancakes", alias: "pancakes"),
                SubCategory(title: "British", alias: "british"),
                SubCategory(title: "Buffets", alias: "buffets"),
                SubCategory(title: "Bulgarian", alias: "bulgarian"),
                SubCategory(title: "Burgers", alias: "burgers"),
                SubCategory(title: "Burmese", alias: "burmese"),
                SubCategory(title: "Cafes", alias: "cafes"),
                SubCategory(title: "Themed Cafes", alias: "themedcafes"),
                SubCategory(title: "Cafeteria", alias: "cafeteria"),
                SubCategory(title: "Cajun/Creole", alias: "cajuncreole"),
                SubCategory(title: "Cambodian", alias: "cambodian"),
                SubCategory(title: "Canadian (New)", alias: "canadiannew"),
                SubCategory(title: "Canteen", alias: "canteen"),
                SubCategory(title: "Caribbean", alias: "caribbean"),
                SubCategory(title: "Dominican", alias: "dominican"),
                SubCategory(title: "Haitian", alias: "haitian"),
                SubCategory(title: "Puerto Rican", alias: "puertorican"),
                SubCategory(title: "Trinidadian", alias: "trinidadian"),
                SubCategory(title: "Catalan", alias: "catalan"),
                SubCategory(title: "Cheesesteaks", alias: "cheesesteaks"),
                SubCategory(title: "Chicken Shop", alias: "chickenshop"),
                SubCategory(title: "Chicken Wings", alias: "chickenwings"),
                SubCategory(title: "Chilean", alias: "chilean"),
                SubCategory(title: "Chinese", alias: "chinese"),
                SubCategory(title: "Cantonese", alias: "cantonese"),
                SubCategory(title: "Congee", alias: "congee"),
                SubCategory(title: "Dim Sum", alias: "dimsum"),
                SubCategory(title: "Fuzhou", alias: "fuzhou"),
                SubCategory(title: "Hainan", alias: "hainan"),
                SubCategory(title: "Hakka", alias: "hakka"),
                SubCategory(title: "Henghwa", alias: "henghwa"),
                SubCategory(title: "Hokkien", alias: "hokkien"),
                SubCategory(title: "Hunan", alias: "hunan"),
                SubCategory(title: "Pekinese", alias: "pekinese"),
                SubCategory(title: "Shanghainese", alias: "shanghainese"),
                SubCategory(title: "Szechuan", alias: "szechuan"),
                SubCategory(title: "Teochew", alias: "teochew"),
                SubCategory(title: "Comfort Food", alias: "comfortfood"),
                SubCategory(title: "Corsican", alias: "corsican"),
                SubCategory(title: "Creperies", alias: "creperies"),
                SubCategory(title: "Cuban", alias: "cuban"),
                SubCategory(title: "Curry Sausage", alias: "currysausage"),
                SubCategory(title: "Cypriot", alias: "cypriot"),
                SubCategory(title: "Czech", alias: "czech"),
                SubCategory(title: "Czech/Slovakian", alias: "czechslovakian"),
                SubCategory(title: "Danish", alias: "danish"),
                SubCategory(title: "Delis", alias: "delis"),
                SubCategory(title: "Diners", alias: "diners"),
                SubCategory(title: "Dinner Theater", alias: "dinnertheater"),
                SubCategory(title: "Dumplings", alias: "dumplings"),
                SubCategory(title: "Eastern European", alias: "easterneuropean"),
                SubCategory(title: "Eritrean", alias: "eritrean"),
                SubCategory(title: "Ethiopian", alias: "ethiopian"),
                SubCategory(title: "Fast Food", alias: "fastfood"),
                SubCategory(title: "Filipino", alias: "filipino"),
                SubCategory(title: "Fischbroetchen", alias: "fischbroetchen"),
                SubCategory(title: "Fish & Chips", alias: "fishchips"),
                SubCategory(title: "Flatbread", alias: "flatbread"),
                SubCategory(title: "Fondue", alias: "fondue"),
                SubCategory(title: "Food Court", alias: "foodcourt"),
                SubCategory(title: "Food Stands", alias: "foodstands"),
                SubCategory(title: "Freiduria", alias: "freiduria"),
                SubCategory(title: "French", alias: "french"),
                SubCategory(title: "Alsatian", alias: "alsatian"),
                SubCategory(title: "Auvergnat", alias: "auvergnat"),
                SubCategory(title: "Berrichon", alias: "berrichon"),
                SubCategory(title: "Bourguignon", alias: "bourguignon"),
                SubCategory(title: "Mauritius", alias: "mauritius"),
                SubCategory(title: "Nicoise", alias: "nicoise"),
                SubCategory(title: "Provencal", alias: "provencal"),
                SubCategory(title: "French Southwest", alias: "frenchsouthwest"),
                SubCategory(title: "Galician", alias: "galician"),
                SubCategory(title: "Game Meat", alias: "gamemeat"),
                SubCategory(title: "Gastropubs", alias: "gastropubs"),
                SubCategory(title: "Georgian", alias: "georgian"),
                SubCategory(title: "German", alias: "german"),
                SubCategory(title: "Baden", alias: "baden"),
                SubCategory(title: "Eastern German", alias: "easterngerman"),
                SubCategory(title: "Franconian", alias: "franconian"),
                SubCategory(title: "Hessian", alias: "hessian"),
                SubCategory(title: "Northern German", alias: "northerngerman"),
                SubCategory(title: "Palatine", alias: "palatine"),
                SubCategory(title: "Rhinelandian", alias: "rhinelandian"),
                SubCategory(title: "Giblets", alias: "giblets"),
                SubCategory(title: "Gluten-Free", alias: "glutenfree"),
                SubCategory(title: "Greek", alias: "greek"),
                SubCategory(title: "Guamanian", alias: "guamanian"),
                SubCategory(title: "Halal", alias: "halal"),
                SubCategory(title: "Hawaiian", alias: "hawaiian"),
                SubCategory(title: "Heuriger", alias: "heuriger"),
                SubCategory(title: "Himalayan/Nepalese", alias: "himalayannepalese"),
                SubCategory(title: "Honduran", alias: "honduran"),
                SubCategory(title: "Hong Kong Style Cafe", alias: "hongkongstylecafe"),
                SubCategory(title: "Hot Dogs", alias: "hotdogs"),
                SubCategory(title: "Hot Pot", alias: "hotpot"),
                SubCategory(title: "Hungarian", alias: "hungarian"),
                SubCategory(title: "Iberian", alias: "iberian"),
                SubCategory(title: "Indian", alias: "indian"),
                SubCategory(title: "Indonesian", alias: "indonesian"),
                SubCategory(title: "International", alias: "international"),
                SubCategory(title: "Irish", alias: "irish"),
                SubCategory(title: "Island Pub", alias: "islandpub"),
                SubCategory(title: "Israeli", alias: "israeli"),
                SubCategory(title: "Italian", alias: "italian"),
                SubCategory(title: "Abruzzese", alias: "abruzzese"),
                SubCategory(title: "Altoatesine", alias: "altoatesine"),
                SubCategory(title: "Apulian", alias: "apulian"),
                SubCategory(title: "Calabrian", alias: "calabrian"),
                SubCategory(title: "Cucina Campana", alias: "cucinacampana"),
                SubCategory(title: "Emilian", alias: "emilian"),
                SubCategory(title: "Friulan", alias: "friulan"),
                SubCategory(title: "Ligurian", alias: "ligurian"),
                SubCategory(title: "Lumbard", alias: "lumbard"),
                SubCategory(title: "Napoletana", alias: "napoletana"),
                SubCategory(title: "Piemonte", alias: "piemonte"),
                SubCategory(title: "Roman", alias: "roman"),
                SubCategory(title: "Sardinian", alias: "sardinian"),
                SubCategory(title: "Sicilian", alias: "sicilian"),
                SubCategory(title: "Tuscan", alias: "tuscan"),
                SubCategory(title: "Venetian", alias: "venetian"),
                SubCategory(title: "Japanese", alias: "japanese"),
                SubCategory(title: "Blowfish", alias: "blowfish"),
                SubCategory(title: "Conveyor Belt Sushi", alias: "conveyorbeltushi"),
                SubCategory(title: "Donburi", alias: "donburi"),
                SubCategory(title: "Gyudon", alias: "gyudon"),
                SubCategory(title: "Oyakodon", alias: "oyakodon"),
                SubCategory(title: "Hand Rolls", alias: "handrolls"),
                SubCategory(title: "Horumon", alias: "horumon"),
                SubCategory(title: "Izakaya", alias: "izakaya"),
                SubCategory(title: "Japanese Curry", alias: "japanesecurry"),
                SubCategory(title: "Kaiseki", alias: "kaiseki"),
                SubCategory(title: "Kushikatsu", alias: "kushikatsu"),
                SubCategory(title: "Oden", alias: "oden"),
                SubCategory(title: "Okinawan", alias: "okinawan"),
                SubCategory(title: "Okonomiyaki", alias: "okonomiyaki"),
                SubCategory(title: "Onigiri", alias: "onigiri"),
                SubCategory(title: "Ramen", alias: "ramen"),
                SubCategory(title: "Robatayaki", alias: "robatayaki"),
                SubCategory(title: "Soba", alias: "soba"),
                SubCategory(title: "Sukiyaki", alias: "sukiyaki"),
                SubCategory(title: "Takoyaki", alias: "takoyaki"),
                SubCategory(title: "Tempura", alias: "tempura"),
                SubCategory(title: "Teppanyaki", alias: "teppanyaki"),
                SubCategory(title: "Tonkatsu", alias: "tonkatsu"),
                SubCategory(title: "Udon", alias: "udon"),
                SubCategory(title: "Unagi", alias: "unagi"),
                SubCategory(title: "Western Style Japanese Food", alias: "westernstylejapanesefood"),
                SubCategory(title: "Yakiniku", alias: "yakiniku"),
                SubCategory(title: "Yakitori", alias: "yakitori"),
                SubCategory(title: "Jewish", alias: "jewish"),
                SubCategory(title: "Kebab", alias: "kebab"),
                SubCategory(title: "Kopitiam", alias: "kopitiam"),
                SubCategory(title: "Korean", alias: "korean"),
                SubCategory(title: "Kosher", alias: "kosher"),
                SubCategory(title: "Kurdish", alias: "kurdish"),
                SubCategory(title: "Laos", alias: "laos"),
                SubCategory(title: "Laotian", alias: "laotian"),
                SubCategory(title: "Latin American", alias: "latinamerican"),
                SubCategory(title: "Colombian", alias: "colombian"),
                SubCategory(title: "Salvadoran", alias: "salvadoran"),
                SubCategory(title: "Venezuelan", alias: "venezuelan"),
                SubCategory(title: "Live/Raw Food", alias: "liverawfood"),
                SubCategory(title: "Lyonnais", alias: "lyonnais"),
                SubCategory(title: "Malaysian", alias: "malaysian"),
                SubCategory(title: "Mamak", alias: "mamak"),
                SubCategory(title: "Nyonya", alias: "nyonya"),
                SubCategory(title: "Meatballs", alias: "meatballs"),
                SubCategory(title: "Mediterranean", alias: "mediterranean"),
                SubCategory(title: "Falafel", alias: "falafel"),
                SubCategory(title: "Mexican", alias: "mexican"),
                SubCategory(title: "Eastern Mexican", alias: "easternmexican"),
                SubCategory(title: "Jaliscan", alias: "jaliscan"),
                SubCategory(title: "Northern Mexican", alias: "northernmexican"),
                SubCategory(title: "Oaxacan", alias: "oaxacan"),
                SubCategory(title: "Pueblan", alias: "pueblan"),
                SubCategory(title: "Tacos", alias: "tacos"),
                SubCategory(title: "Tamales", alias: "tamales"),
                SubCategory(title: "Yucatan", alias: "yucatan"),
                SubCategory(title: "Middle Eastern", alias: "middleeastern"),
                SubCategory(title: "Egyptian", alias: "egyptian"),
                SubCategory(title: "Lebanese", alias: "lebanese"),
                SubCategory(title: "Milk Bars", alias: "milkbars"),
                SubCategory(title: "Modern Australian", alias: "modernaustralian"),
                SubCategory(title: "Modern European", alias: "moderneuropean"),
                SubCategory(title: "Mongolian", alias: "mongolian"),
                SubCategory(title: "Moroccan", alias: "moroccan"),
                SubCategory(title: "New Mexican Cuisine", alias: "newmexicancuisine"),
                SubCategory(title: "New Zealand", alias: "newzealand"),
                SubCategory(title: "Nicaraguan", alias: "nicaraguan"),
                SubCategory(title: "Night Food", alias: "nightfood"),
                SubCategory(title: "Nikkei", alias: "nikkei"),
                SubCategory(title: "Noodles", alias: "noodles"),
                SubCategory(title: "Norcinerie", alias: "norcinerie"),
                SubCategory(title: "Open Sandwiches", alias: "opensandwiches"),
                SubCategory(title: "Oriental", alias: "oriental"),
                SubCategory(title: "Pakistani", alias: "pakistani"),
                SubCategory(title: "Pan Asian", alias: "panasian"),
                SubCategory(title: "Parent Cafes", alias: "parentcafes"),
                SubCategory(title: "Parma", alias: "parma"),
                SubCategory(title: "Peruvian", alias: "peruvian"),
                SubCategory(title: "PF/Comercial", alias: "pfcomercial"),
                SubCategory(title: "Pita", alias: "pita"),
                SubCategory(title: "Pizza", alias: "pizza"),
                SubCategory(title: "Polish", alias: "polish"),
                SubCategory(title: "Pierogis", alias: "pierogis"),
                SubCategory(title: "Polynesian", alias: "polynesian"),
                SubCategory(title: "Pop-Up Restaurants", alias: "popuprestaurants"),
                SubCategory(title: "Portuguese", alias: "portuguese"),
                SubCategory(title: "Alentejo", alias: "alentejo"),
                SubCategory(title: "Algarve", alias: "algarve"),
                SubCategory(title: "Azores", alias: "azores"),
                SubCategory(title: "Beira", alias: "beira"),
                SubCategory(title: "Fado Houses", alias: "fadohouses"),
                SubCategory(title: "Madeira", alias: "madeira"),
                SubCategory(title: "Minho", alias: "minho"),
                SubCategory(title: "Ribatejo", alias: "ribatejo"),
                SubCategory(title: "Tras-os-Montes", alias: "trasosmontes"),
                SubCategory(title: "Potatoes", alias: "potatoes"),
                SubCategory(title: "Poutineries", alias: "poutineries"),
                SubCategory(title: "Pub Food", alias: "pubfood"),
                SubCategory(title: "Rice", alias: "rice"),
                SubCategory(title: "Romanian", alias: "romanian"),
                SubCategory(title: "Rotisserie Chicken", alias: "rotisseriechicken"),
                SubCategory(title: "Russian", alias: "russian"),
                SubCategory(title: "Salad", alias: "salad"),
                SubCategory(title: "Sandwiches", alias: "sandwiches"),
                SubCategory(title: "Scandinavian", alias: "scandinavian"),
                SubCategory(title: "Schnitzel", alias: "schnitzel"),
                SubCategory(title: "Scottish", alias: "scottish"),
                SubCategory(title: "Seafood", alias: "seafood"),
                SubCategory(title: "Serbo Croatian", alias: "serbocroatian"),
                SubCategory(title: "Signature Cuisine", alias: "signaturecuisine"),
                SubCategory(title: "Singaporean", alias: "singaporean"),
                SubCategory(title: "Slovakian", alias: "slovakian"),
                SubCategory(title: "Somali", alias: "somali"),
                SubCategory(title: "Soul Food", alias: "soulfood"),
                SubCategory(title: "Soup", alias: "soup"),
                SubCategory(title: "Southern", alias: "southern"),
                SubCategory(title: "Spanish", alias: "spanish"),
                SubCategory(title: "Arroceria/Paella", alias: "arroceriapaella"),
                SubCategory(title: "Sri Lankan", alias: "srilankan"),
                SubCategory(title: "Steakhouses", alias: "steakhouses"),
                SubCategory(title: "Supper Clubs", alias: "supperclubs"),
                SubCategory(title: "Sushi Bars", alias: "sushibars"),
                SubCategory(title: "Swabian", alias: "swabian"),
                SubCategory(title: "Swedish", alias: "swedish"),
                SubCategory(title: "Swiss Food", alias: "swissfood"),
                SubCategory(title: "Syrian", alias: "syrian"),
                SubCategory(title: "Tabernas", alias: "tabernas"),
                SubCategory(title: "Taiwanese", alias: "taiwanese"),
                SubCategory(title: "Tapas Bars", alias: "tapasbars"),
                SubCategory(title: "Tapas/Small Plates", alias: "tapassmallplates"),
                SubCategory(title: "Tavola Calda", alias: "tavolacalda"),
                SubCategory(title: "Tex-Mex", alias: "texmex"),
                SubCategory(title: "Thai", alias: "thai"),
                SubCategory(title: "Traditional Norwegian", alias: "traditionalnorwegian"),
                SubCategory(title: "Traditional Swedish", alias: "traditionalswedish"),
                SubCategory(title: "Trattorie", alias: "trattorie"),
                SubCategory(title: "Turkish", alias: "turkish"),
                SubCategory(title: "Chee Kufta", alias: "cheeku"),
                SubCategory(title: "Gozleme", alias: "gozleme"),
                SubCategory(title: "Homemade Food", alias: "homemadefood"),
                SubCategory(title: "Lahmacun", alias: "lahmacun"),
                SubCategory(title: "Ottoman Cuisine", alias: "ottomancuisine"),
                SubCategory(title: "Turkish Ravioli", alias: "turkishravioli"),
                SubCategory(title: "Ukrainian", alias: "ukrainian"),
                SubCategory(title: "Uzbek", alias: "uzbek"),
                SubCategory(title: "Vegan", alias: "vegan"),
                SubCategory(title: "Vegetarian", alias: "vegetarian"),
                SubCategory(title: "Venison", alias: "venison"),
                SubCategory(title: "Vietnamese", alias: "vietnamese"),
                SubCategory(title: "Waffles", alias: "waffles"),
                SubCategory(title: "Wok", alias: "wok"),
                SubCategory(title: "Wraps", alias: "wraps"),
                SubCategory(title: "Yugoslav", alias: "yugoslav")
            ]),
            YelpCategory(name: "Relax", subCategories: [
                SubCategory(title: "Acne Treatment", alias: "acnetreatment"),
                SubCategory(title: "Barbers", alias: "barbers"),
                SubCategory(title: "Cosmetics & Beauty Supply", alias: "cosmeticsbeautysupply"),
                SubCategory(title: "Day Spas", alias: "dayspas"),
                SubCategory(title: "Erotic Massage", alias: "eroticmassage"),
                SubCategory(title: "Eyebrow Services", alias: "eyebrowservices"),
                SubCategory(title: "Eyelash Service", alias: "eyelashservice"),
                SubCategory(title: "Foot Care", alias: "footcare"),
                SubCategory(title: "Hair Extensions", alias: "hairextensions"),
                SubCategory(title: "Hair Loss Centers", alias: "hairlosscenters"),
                SubCategory(title: "Hair Removal", alias: "hairremoval"),
                SubCategory(title: "Laser Hair Removal", alias: "laserhairremoval"),
                SubCategory(title: "Sugaring", alias: "sugaring"),
                SubCategory(title: "Threading Services", alias: "threadingservices"),
                SubCategory(title: "Waxing", alias: "waxing"),
                SubCategory(title: "Hair Salons", alias: "hairsalons"),
                SubCategory(title: "Blow Dry/Out Services", alias: "blowdryoutservices"),
                SubCategory(title: "Hair Stylists", alias: "hairstylists"),
                SubCategory(title: "Kids Hair Salons", alias: "kidshairsalons"),
                SubCategory(title: "Men’s Hair Salons", alias: "menshairsalons"),
                SubCategory(title: "Hot Springs", alias: "hotsprings"),
                SubCategory(title: "Makeup Artists", alias: "makeupartists"),
                SubCategory(title: "Massage", alias: "massage"),
                SubCategory(title: "Medical Spas", alias: "medicalspas"),
                SubCategory(title: "Nail Salons", alias: "nailsalons"),
                SubCategory(title: "Nail Technicians", alias: "nailtechnicians"),
                SubCategory(title: "Perfume", alias: "perfume"),
                SubCategory(title: "Permanent Makeup", alias: "permanentmakeup"),
                SubCategory(title: "Piercing", alias: "piercing"),
                SubCategory(title: "Skin Care", alias: "skincare"),
                SubCategory(title: "Estheticians", alias: "estheticians"),
                SubCategory(title: "Tanning", alias: "tanning"),
                SubCategory(title: "Spray Tanning", alias: "spraytanning"),
                SubCategory(title: "Tanning Beds", alias: "tanningbeds"),
                SubCategory(title: "Tattoo", alias: "tattoo"),
                SubCategory(title: "Teeth Whitening", alias: "teethwhitening")
            ]),
            YelpCategory(name: "Leisure", subCategories: [
                SubCategory(title: "Arcades", alias: "arcades"),
                SubCategory(title: "Art Galleries", alias: "artgalleries"),
                SubCategory(title: "Bingo Halls", alias: "bingohalls"),
                SubCategory(title: "Botanical Gardens", alias: "botanicalgardens"),
                SubCategory(title: "Cabaret", alias: "cabaret"),
                SubCategory(title: "Casinos", alias: "casinos"),
                SubCategory(title: "Cinema", alias: "cinema"),
                SubCategory(title: "Drive-In Theater", alias: "driveintheater"),
                SubCategory(title: "Outdoor Movies", alias: "outdoormovies"),
                SubCategory(title: "Country Clubs", alias: "countryclubs"),
                SubCategory(title: "Cultural Center", alias: "culturalcenter"),
                SubCategory(title: "Entertainment", alias: "entertainment"),
                SubCategory(title: "Farms", alias: "farms"),
                SubCategory(title: "Attraction Farms", alias: "attractionfarms"),
                SubCategory(title: "Pick Your Own Farms", alias: "pickyourownfarms"),
                SubCategory(title: "Ranches", alias: "ranches"),
                SubCategory(title: "Festivals", alias: "festivals"),
                SubCategory(title: "Haunted Houses", alias: "hauntedhouses"),
                SubCategory(title: "Jazz & Blues", alias: "jazzblues"),
                SubCategory(title: "LAN Centers", alias: "lancenters"),
                SubCategory(title: "Makerspaces", alias: "makerspaces"),
                SubCategory(title: "Museums", alias: "museums"),
                SubCategory(title: "Art Museums", alias: "artmuseums"),
                SubCategory(title: "Children’s Museums", alias: "childrensmuseums"),
                SubCategory(title: "Music Venues", alias: "musicvenues"),
                SubCategory(title: "Observatories", alias: "observatories"),
                SubCategory(title: "Opera & Ballet", alias: "operaballet"),
                SubCategory(title: "Paint & Sip", alias: "paintsip"),
                SubCategory(title: "Performing Arts", alias: "performingarts"),
                SubCategory(title: "Planetarium", alias: "planetarium"),
                SubCategory(title: "Professional Sports Teams", alias: "professionalsportsteams"),
                SubCategory(title: "Race Tracks", alias: "racetracks"),
                SubCategory(title: "Rodeo", alias: "rodeo"),
                SubCategory(title: "Social Clubs", alias: "socialclubs"),
                SubCategory(title: "Veterans Organizations", alias: "veteransorganizations"),
                SubCategory(title: "Sports Betting", alias: "sportsbetting"),
                SubCategory(title: "Stadiums & Arenas", alias: "stadiumsarenas"),
                SubCategory(title: "Studio Taping", alias: "studiotaping"),
                SubCategory(title: "Supernatural Readings", alias: "supernaturalreadings"),
                SubCategory(title: "Astrologers", alias: "astrologers"),
                SubCategory(title: "Mystics", alias: "mystics"),
                SubCategory(title: "Psychic Mediums", alias: "psychicmediums"),
                SubCategory(title: "Psychics", alias: "psychics"),
                SubCategory(title: "Tablao Flamenco", alias: "tablaoflamenco"),
                SubCategory(title: "Ticket Sales", alias: "ticketsales"),
                SubCategory(title: "Virtual Reality Centers", alias: "virtualrealitycenters"),
                SubCategory(title: "Wineries", alias: "wineries"),
                SubCategory(title: "Wine Tasting Room", alias: "winetastingroom")
            ]),
            YelpCategory(name: "Local", subCategories: [
                SubCategory(title: "Parklets", alias: "parklets"),
                SubCategory(title: "Public Art", alias: "publicart"),
                SubCategory(title: "Unofficial Yelp Events", alias: "unofficialyelpevents"),
                SubCategory(title: "Yelp Events", alias: "yelpevents")
            ])
        ]
    }
    
    
    func incrementSubCategory(yelpBigCat: String, subCategoryName: String) {
        guard let categoryIndex = categories.firstIndex(where: { $0.name == yelpBigCat }) else {
            print("Category \(yelpBigCat) not found.")
            return
        }
        guard let subCategoryIndex = categories[categoryIndex].subCategories.firstIndex(where: { $0.title == subCategoryName }) else {
            print("Subcategory \(subCategoryName) not found in category \(yelpBigCat).")
            return
        }
        
        categories[categoryIndex].subCategories[subCategoryIndex].count += 1
        print("Incremented count for subcategory \(subCategoryName) in category \(yelpBigCat). New count: \(categories[categoryIndex].subCategories[subCategoryIndex].count)")
    }
    
    func getTopThree(for categoryName: String) {
        if let category = categories.first(where: { $0.name == categoryName }) {
            let topThree = category.subCategories.sorted { $0.count > $1.count }.prefix(3)
            let topThreeNames = topThree.map { $0.title }
            print("Top three subcategories for \(category.name): \(topThreeNames)")
        } else {
            print("Category \(categoryName) not found.")
        }
    }
}



struct RandomCategory {
    let activities : [String] = ["airsoft", "amateursportsteams", "amusementparks", "aquariums", "archery", "atvrentals/tours", "axethrowing", "badminton", "baseballfields", "basketballcourts", "bathingarea", "battingcages", "beachvolleyball", "beaches", "bicyclepaths", "bikeparking", "boating", "bobsledding", "bocceball", "bowling", "bubblesoccer", "bungeejumping", "canyoneering", "challengecourses", "climbing", "cyclingclasses", "dartarenas", "discgolf", "diving", "freediving", "scubadiving", "escapegames", "fencingclubs", "fishing", "fitness&instruction", "aerialfitness", "barreclasses", "boxing", "cardioclasses", "dancestudios", "golflessons", "gyms", "circuittraininggyms", "intervaltraininggyms", "martialarts", "brazilianjiu-jitsu", "chinesemartialarts", "karate", "kickboxing", "muaythai", "taekwondo", "meditationcenters", "pilates", "qigong", "self-defenseclasses", "swimminglessons/schools", "taichi", "trainers", "yoga", "flyboarding", "gliding", "gokarts", "golf", "gun/rifleranges", "gymnastics", "handball", "hanggliding", "hiking", "horseracing", "horsebackriding", "hotairballoons", "indoorplaycentre", "jetskis", "kiteboarding", "lakes", "lasertag", "lawnbowling", "minigolf", "mountainbiking", "nudist", "paddleboarding", "paintball", "paragliding", "parasailing", "parks", "dogparks", "skateparks", "pickleball", "playgrounds", "publicplazas", "races&competitions", "racingexperience", "rafting/kayaking", "recreationcenters", "rockclimbing", "sailing", "scavengerhunts", "scooterrentals", "skatingrinks", "skiing", "skydiving", "sledding", "snorkeling", "soccer", "sportsclubs", "surfing", "swimmingpools", "tennis", "trampolineparks", "tubing", "volleyball", "waterparks", "wildlifehuntingranges", "ziplining", "zoos", "pettingzoos", "zorbing","arcades", "artgalleries", "bingohalls", "cabaret", "casinos", "cinema", "drive-intheater", "outdoormovies", "countryclubs", "culturalcenter", "entertainment", "farms", "attractionfarms", "ranches", "festivals", "hauntedhouses", "jazz&blues", "lancenters", "makerspaces", "museums", "artmuseums", "musicvenues", "observatories", "opera&ballet", "paint&sip", "performingarts", "planetarium", "professionalsportsteams", "racetracks", "rodeo", "socialclubs", "veteransorganizations", "sportsbetting", "stadiums&arenas", "studiotaping", "supernaturalreadings", "astrologers", "mystics", "psychicmediums", "psychics", "tablaoflamenco", "ticketsales", "virtualrealitycenters", "wineries", "winetastingroom","acnetreatment", "barbers", "cosmetics&beautysupply", "dayspas", "eroticmassage", "eyebrowservices", "eyelashservice", "footcare", "hairextensions", "hairlosscenters", "hairremoval", "laserhairremoval", "sugaring", "threadingservices", "waxing", "hairsalons", "blowdry/outservices", "hairextensions", "hairstylists", "men’shairsalons", "hotsprings", "makeupartists", "massage", "medicalspas", "nailsalons", "nailtechnicians", "perfume", "permanentmakeup", "piercing", "skincare", "estheticians", "tanning", "spraytanning", "tanningbeds", "tattoo","acaibowls", "backshop", "bagels", "bakeries", "beer,wine&spirits", "bento", "beveragestore", "breweries", "brewpubs", "bubbletea", "butcher", "chimneycakes", "churros", "cideries", "coffee&tea", "coffee&teasupplies", "coffeeroasteries", "conveniencestores", "csa", "cupcakes", "customcakes", "delicatessen", "desserts", "distilleries", "do-it-yourselffood", "donairs", "donuts", "empanadas", "ethicalgrocery", "farmersmarket", "fishmonger", "fooddeliveryservices", "foodtrucks", "friterie", "gelato", "grocery", "hawkercentre", "honey", "icecream&frozenyogurt", "importedfood", "internationalgrocery", "internetcafes", "japanesesweets", "taiyaki", "juicebars&smoothies", "kiosk", "kombucha", "meaderies", "milkshakebars", "mulledwine", "nasilemak", "organicstores", "panzerotti", "parentcafes", "patisserie/cakeshop", "piadina", "poke", "pretzels", "salumerie", "shavedice", "shavedsnow", "smokehouse", "specialtyfood", "candystores", "cheeseshops", "chocolatiers&shops", "dagashi", "driedfruit", "frozenfood", "fruits&veggies", "healthmarkets", "herbs&spices", "macarons", "meatshops", "pastashops", "popcornshops", "seafoodmarkets", "tofushops", "streetvendors", "sugarshacks", "tearooms", "torshi", "tortillas", "waterstores", "wineries", "zapiekanka", "adultentertainment", "stripclubs", "stripteasedancers", "barcrawl", "bars", "beerbar", "champagnebars", "cigarbars", "cocktailbars", "divebars", "drive-thrubars", "gaybars", "hookahbars", "irishpub", "lounges", "pubs", "speakeasies", "sportsbars", "tikibars", "vermouthbars", "whiskeybars", "winebars", "beergardens", "clubcrawl", "comedyclubs", "countrydancehalls", "danceclubs", "jazz&blues", "karaoke", "musicvenues", "pianobars", "poolhalls","afghan", "african", "senegalese", "southafrican", "american(new)", "american(traditional)", "andalusian", "arabian", "arabpizza", "argentine", "armenian", "asianfusion", "asturian", "australian", "austrian", "baguettes", "bangladeshi", "barbeque", "basque", "bavarian", "beergarden", "beerhall", "beisl", "belgian", "flemish", "bistros", "blacksea", "brasseries", "brazilian", "brazilianempanadas", "centralbrazilian", "northeasternbrazilian", "northernbrazilian", "rodizios", "breakfast&brunch", "pancakes", "british", "buffets", "bulgarian", "burgers", "burmese", "cafes", "themedcafes", "cafeteria", "cajun/creole", "cambodian", "canadian(new)", "canteen", "caribbean", "dominican", "haitian", "puertorican", "trinidadian", "catalan", "cheesesteaks", "chickenshop", "chickenwings", "chilean", "chinese", "cantonese", "congee", "dimsum", "fuzhou", "hainan", "hakka", "henghwa", "hokkien", "hunan", "pekinese", "shanghainese", "szechuan", "teochew", "comfortfood", "corsican", "creperies", "cuban", "currysausage", "cypriot", "czech", "czech/slovakian", "danish", "delis", "diners", "dinnertheater", "dumplings", "easterneuropean", "eritrean", "ethiopian", "fastfood", "filipino", "fischbroetchen", "fish&chips", "flatbread", "fondue", "foodcourt", "foodstands", "freiduria", "french", "alsatian", "auvergnat", "berrichon", "bourguignon", "mauritius", "nicoise", "provencal", "frenchsouthwest", "galician", "gamemeat", "gastropubs", "georgian", "german", "baden", "easterngerman", "franconian", "hessian", "northerngerman", "palatine", "rhinelandian", "giblets", "gluten-free", "greek", "guamanian", "halal", "hawaiian", "heuriger", "himalayan/nepalese", "honduran", "hongkongstylecafe", "hotdogs", "hotpot", "hungarian", "iberian", "indian", "indonesian", "international", "irish", "islandpub", "israeli", "italian", "abruzzese", "altoatesine", "apulian", "calabrian", "cucinacampana", "emilian", "friulan", "ligurian", "lumbard", "napoletana", "piemonte", "roman", "sardinian", "sicilian", "tuscan", "venetian", "japanese", "blowfish", "conveyorbeltushi", "donburi", "gyudon", "oyakodon", "handrolls", "horumon", "izakaya", "japanesecurry", "kaiseki", "kushikatsu", "oden", "okinawan", "okonomiyaki", "onigiri", "ramen", "robatayaki", "soba", "sukiyaki", "takoyaki", "tempura", "teppanyaki", "tonkatsu", "udon", "unagi", "westernstylejapanesefood", "yakiniku", "yakitori", "jewish", "kebab", "kopitiam", "korean", "kosher", "kurdish", "laos", "laotian", "latinamerican", "colombian", "salvadoran", "venezuelan", "live/rawfood", "lyonnais", "malaysian", "mamak", "nyonya", "meatballs", "mediterranean", "falafel", "mexican", "easternmexican", "jaliscan", "northernmexican", "oaxacan", "pueblan", "tacos", "tamales", "yucatan", "middleeastern", "egyptian", "lebanese", "milkbars", "modernaustralian", "moderneuropean", "mongolian", "moroccan", "newmexicancuisine", "newzealand", "nicaraguan", "nightfood", "nikkei", "noodles", "norcinerie", "opensandwiches", "oriental", "pakistani", "panasian", "parentcafes", "parma", "persian/iranian", "peruvian", "pf/comercial", "pita", "pizza", "polish", "pierogis", "polynesian", "pop-uprestaurants", "portuguese", "alentejo", "algarve", "azores", "beira", "fadohouses", "madeira", "minho", "ribatejo", "tras-os-montes", "potatoes", "poutineries", "pubfood", "rice", "romanian", "rotisseriechicken", "russian", "salad", "sandwiches", "scandinavian", "schnitzel", "scottish", "seafood", "serbocroatian", "signaturecuisine", "singaporean", "slovakian", "somali", "soulfood", "soup", "southern", "spanish", "arroceria/paella", "srilankan", "steakhouses", "supperclubs", "sushibars", "swabian", "swedish", "swissfood", "syrian", "tabernas", "taiwanese", "tapasbars", "tapas/smallplates", "tavolacalda", "tex-mex", "thai", "traditionalnorwegian", "traditionalwedish", "trattorie", "turkish", "cheeku", "gozleme", "lahmacun", "ottomancuisine", "turkishravioli", "ukrainian", "uzbek", "vegan", "vegetarian", "venison", "vietnamese", "waffles", "wok", "wraps", "yugoslav","parklets", "publicart", "unofficialyelpevents", "yelpevents"]
}
