//
//  CategoryManager.swift
//  tori
//
//  Created by Fahad Munawar on 5/15/24.
//

import Foundation
import SwiftUI
import SwiftData

enum yelpCategories: String, CaseIterable{
    
    case activeLife = "Active"
    case arts = "Leisure"
    case beauty = "Relax"
    case food = "Food"
    case nightLife = "Night"
//    case shopping = "Shop"
//    case restaurants = "Restaurants"
    case localFlavor = "Local"
    
    var background: Color {
        switch self {
        default:
                .gray
        }
    }
    
    var icon: String {
        switch self {
        case .activeLife:
            "figure.cooldown"
        case .arts:
            "pencil.and.scribble"
        case .beauty:
            "bubbles.and.sparkles.fill"
        case .food:
            "fork.knife"
        case .nightLife:
            "music.quarternote.3"
//        case .shopping:
//            "storefront"
        default:
            "figure"
        }
    }
    
//    var subCategories: [String: Int] {
//        switch self {
//        case .activeLife: [
//            "Airsoft": 0,
//            "Amateur Sports Teams": 0,
//            "Amusement Parks": 0,
//            "Aquariums": 0,
//            "Archery": 0,
//            "ATV Rentals/Tours": 0,
//            "Axe Throwing": 0,
//            "Badminton": 0,
//            "Baseball Fields": 0,
//            "Basketball Courts": 0,
//            "Bathing Area": 0,
//            "Batting Cages": 0,
//            "Beach Equipment Rentals": 0,
//            "Beach Volleyball": 0,
//            "Beaches": 0,
//            "Bicycle Paths": 0,
//            "Bike Parking": 0,
//            "Bike Rentals": 0,
//            "Boating": 0,
//            "Bobsledding": 0,
//            "Bocce Ball": 0,
//            "Bowling": 0,
//            "Bubble Soccer": 0,
//            "Bungee Jumping": 0,
//            "Canyoneering": 0,
//            "Carousels": 0,
//            "Challenge Courses": 0,
//            "Climbing": 0,
//            "Cycling Classes": 0,
//            "Dart Arenas": 0,
//            "Disc Golf": 0,
//            "Diving": 0,
//            "Free Diving": 0,
//            "Scuba Diving": 0,
//            "Escape Games": 0,
//            "Fencing Clubs": 0,
//            "Fishing": 0,
//            "Fitness & Instruction": 0,
//            "Aerial Fitness": 0,
//            "Barre Classes": 0,
//            "Boxing": 0,
//            "Cardio Classes": 0,
//            "Dance Studios": 0,
//            "Golf Lessons": 0,
//            "Gyms": 0,
//            "Circuit Training Gyms": 0,
//            "Interval Training Gyms": 0,
//            "Martial Arts": 0,
//            "Brazilian Jiu-jitsu": 0,
//            "Chinese Martial Arts": 0,
//            "Karate": 0,
//            "Kickboxing": 0,
//            "Muay Thai": 0,
//            "Taekwondo": 0,
//            "Meditation Centers": 0,
//            "Pilates": 0,
//            "Qi Gong": 0,
//            "Self-defense Classes": 0,
//            "Swimming Lessons/Schools": 0,
//            "Tai Chi": 0,
//            "Trainers": 0,
//            "Yoga": 0,
//            "Flyboarding": 0,
//            "Gliding": 0,
//            "Go Karts": 0,
//            "Golf": 0,
//            "Gun/Rifle Ranges": 0,
//            "Gymnastics": 0,
//            "Handball": 0,
//            "Hang Gliding": 0,
//            "Hiking": 0,
//            "Horse Racing": 0,
//            "Horseback Riding": 0,
//            "Hot Air Balloons": 0,
//            "Indoor Playcentre": 0,
//            "Jet Skis": 0,
//            "Kids Activities": 0,
//            "Kiteboarding": 0,
//            "Lakes": 0,
//            "Laser Tag": 0,
//            "Lawn Bowling": 0,
//            "Mini Golf": 0,
//            "Mountain Biking": 0,
//            "Nudist": 0,
//            "Paddleboarding": 0,
//            "Paintball": 0,
//            "Paragliding": 0,
//            "Parasailing": 0,
//            "Parks": 0,
//            "Dog Parks": 0,
//            "Skate Parks": 0,
//            "Pickleball": 0,
//            "Playgrounds": 0,
//            "Public Plazas": 0,
//            "Races & Competitions": 0,
//            "Racing Experience": 0,
//            "Rafting/Kayaking": 0,
//            "Recreation Centers": 0,
//            "Rock Climbing": 0,
//            "Sailing": 0,
//            "Scavenger Hunts": 0,
//            "Scooter Rentals": 0,
//            "Senior Centers": 0,
//            "Skating Rinks": 0,
//            "Skiing": 0,
//            "Skydiving": 0,
//            "Sledding": 0,
//            "Snorkeling": 0,
//            "Soccer": 0,
//            "Sport Equipment Hire": 0,
//            "Sports Clubs": 0,
//            "Squash": 0,
//            "Summer Camps": 0,
//            "Surf Lifesaving": 0,
//            "Surfing": 0,
//            "Swimming Pools": 0,
//            "Tennis": 0,
//            "Trampoline Parks": 0,
//            "Tubing": 0,
//            "Volleyball": 0,
//            "Water Parks": 0,
//            "Wildlife Hunting Ranges": 0,
//            "Ziplining": 0,
//            "Zoos": 0,
//            "Petting Zoos": 0,
//            "Zorbing": 0
//        ]
//        case .arts: [
//            "Arcades": 0,
//            "Art Galleries": 0,
//            "Bingo Halls": 0,
//            "Botanical Gardens": 0,
//            "Cabaret": 0,
//            "Casinos": 0,
//            "Cinema": 0,
//            "Drive-In Theater": 0,
//            "Outdoor Movies": 0,
//            "Country Clubs": 0,
//            "Cultural Center": 0,
//            "Entertainment": 0,
//            "Farms": 0,
//            "Attraction Farms": 0,
//            "Pick Your Own Farms": 0,
//            "Ranches": 0,
//            "Festivals": 0,
//            "Haunted Houses": 0,
//            "Jazz & Blues": 0,
//            "LAN Centers": 0,
//            "Makerspaces": 0,
//            "Museums": 0,
//            "Art Museums": 0,
//            "Children’s Museums": 0,
//            "Music Venues": 0,
//            "Observatories": 0,
//            "Opera & Ballet": 0,
//            "Paint & Sip": 0,
//            "Performing Arts": 0,
//            "Planetarium": 0,
//            "Professional Sports Teams": 0,
//            "Race Tracks": 0,
//            "Rodeo": 0,
//            "Social Clubs": 0,
//            "Veterans Organizations": 0,
//            "Sports Betting": 0,
//            "Stadiums & Arenas": 0,
//            "Studio Taping": 0,
//            "Supernatural Readings": 0,
//            "Astrologers": 0,
//            "Mystics": 0,
//            "Psychic Mediums": 0,
//            "Psychics": 0,
//            "Tablao Flamenco": 0,
//            "Ticket Sales": 0,
//            "Virtual Reality Centers": 0,
//            "Wineries": 0,
//            "Wine Tasting Room": 0
//        ]
//        case .beauty: [
//            "Acne Treatment": 0,
//            "Barbers": 0,
//            "Cosmetics & Beauty Supply": 0,
//            "Day Spas": 0,
//            "Erotic Massage": 0,
//            "Eyebrow Services": 0,
//            "Eyelash Service": 0,
//            "Foot Care": 0,
//            "Hair Extensions": 0,
//            "Hair Loss Centers": 0,
//            "Hair Removal": 0,
//            "Laser Hair Removal": 0,
//            "Sugaring": 0,
//            "Threading Services": 0,
//            "Waxing": 0,
//            "Hair Salons": 0,
//            "Blow Dry/Out Services": 0,
//            "Hair Stylists": 0,
//            "Kids Hair Salons": 0,
//            "Men’s Hair Salons": 0,
//            "Hot Springs": 0,
//            "Makeup Artists": 0,
//            "Massage": 0,
//            "Medical Spas": 0,
//            "Nail Salons": 0,
//            "Nail Technicians": 0,
//            "Perfume": 0,
//            "Permanent Makeup": 0,
//            "Piercing": 0,
//            "Skin Care": 0,
//            "Estheticians": 0,
//            "Tanning": 0,
//            "Spray Tanning": 0,
//            "Tanning Beds": 0,
//            "Tattoo": 0,
//            "Teeth Whitening": 0
//        ]
//        case .food: [
//            "Acai Bowls": 0,
//            "Backshop": 0,
//            "Bagels": 0,
//            "Bakeries": 0,
//            "Beer, Wine & Spirits": 0,
//            "Bento": 0,
//            "Beverage Store": 0,
//            "Breweries": 0,
//            "Brewpubs": 0,
//            "Bubble Tea": 0,
//            "Butcher": 0,
//            "Chimney Cakes": 0,
//            "Churros": 0,
//            "Cideries": 0,
//            "Coffee & Tea": 0,
//            "Coffee & Tea Supplies": 0,
//            "Coffee Roasteries": 0,
//            "Convenience Stores": 0,
//            "CSA": 0,
//            "Cupcakes": 0,
//            "Custom Cakes": 0,
//            "Delicatessen": 0,
//            "Desserts": 0,
//            "Distilleries": 0,
//            "Do-It-Yourself Food": 0,
//            "Donairs": 0,
//            "Donuts": 0,
//            "Empanadas": 0,
//            "Ethical Grocery": 0,
//            "Farmers Market": 0,
//            "Fishmonger": 0,
//            "Food Delivery Services": 0,
//            "Food Trucks": 0,
//            "Friterie": 0,
//            "Gelato": 0,
//            "Grocery": 0,
//            "Hawker Centre": 0,
//            "Honey": 0,
//            "Ice Cream & Frozen Yogurt": 0,
//            "Imported Food": 0,
//            "International Grocery": 0,
//            "Internet Cafes": 0,
//            "Japanese Sweets": 0,
//            "Taiyaki": 0,
//            "Juice Bars & Smoothies": 0,
//            "Kiosk": 0,
//            "Kombucha": 0,
//            "Meaderies": 0,
//            "Milkshake Bars": 0,
//            "Mulled Wine": 0,
//            "Nasi Lemak": 0,
//            "Organic Stores": 0,
//            "Panzerotti": 0,
//            "Parent Cafes": 0,
//            "Patisserie/Cake Shop": 0,
//            "Piadina": 0,
//            "Poke": 0,
//            "Pretzels": 0,
//            "Salumerie": 0,
//            "Shaved Ice": 0,
//            "Shaved Snow": 0,
//            "Smokehouse": 0,
//            "Specialty Food": 0,
//            "Candy Stores": 0,
//            "Cheese Shops": 0,
//            "Chocolatiers & Shops": 0,
//            "Dagashi": 0,
//            "Dried Fruit": 0,
//            "Frozen Food": 0,
//            "Fruits & Veggies": 0,
//            "Health Markets": 0,
//            "Herbs & Spices": 0,
//            "Macarons": 0,
//            "Meat Shops": 0,
//            "Olive Oil": 0,
//            "Pasta Shops": 0,
//            "Popcorn Shops": 0,
//            "Seafood Markets": 0,
//            "Tofu Shops": 0,
//            "Street Vendors": 0,
//            "Sugar Shacks": 0,
//            "Tea Rooms": 0,
//            "Torshi": 0,
//            "Tortillas": 0,
//            "Water Stores": 0,
//            "Wineries": 0,
//            "Zapiekanka": 0
//        ]
//        case .localFlavor: [
//            "Parklets" : 0,
//            "Public Art" : 0,
//            "Unofficial Yelp Events" : 0,
//            "Yelp Events" : 0
//        ]
//        case .nightLife: [
//            "Adult Entertainment": 0,
//            "Strip Clubs": 0,
//            "Striptease Dancers": 0,
//            "Bar Crawl": 0,
//            "Bars": 0,
//            "Airport Lounges": 0,
//            "Beer Bar": 0,
//            "Champagne Bars": 0,
//            "Cigar Bars": 0,
//            "Cocktail Bars": 0,
//            "Dive Bars": 0,
//            "Drive-Thru Bars": 0,
//            "Gay Bars": 0,
//            "Hookah Bars": 0,
//            "Irish Pub": 0,
//            "Lounges": 0,
//            "Pubs": 0,
//            "Speakeasies": 0,
//            "Sports Bars": 0,
//            "Tiki Bars": 0,
//            "Vermouth Bars": 0,
//            "Whiskey Bars": 0,
//            "Wine Bars": 0,
//            "Beer Gardens": 0,
//            "Club Crawl": 0,
//            "Comedy Clubs": 0,
//            "Country Dance Halls": 0,
//            "Dance Clubs": 0,
//            "Jazz & Blues": 0,
//            "Karaoke": 0,
//            "Music Venues": 0,
//            "Piano Bars": 0,
//            "Pool Halls": 0
//        ]
//        case .restaurants: [
//            "Afghan": 0,
//            "African": 0,
//            "Senegalese": 0,
//            "South African": 0,
//            "American (New)": 0,
//            "American (Traditional)": 0,
//            "Andalusian": 0,
//            "Arabian": 0,
//            "Arab Pizza": 0,
//            "Argentine": 0,
//            "Armenian": 0,
//            "Asian Fusion": 0,
//            "Asturian": 0,
//            "Australian": 0,
//            "Austrian": 0,
//            "Baguettes": 0,
//            "Bangladeshi": 0,
//            "Barbeque": 0,
//            "Basque": 0,
//            "Bavarian": 0,
//            "Beer Garden": 0,
//            "Beer Hall": 0,
//            "Beisl": 0,
//            "Belgian": 0,
//            "Flemish": 0,
//            "Bistros": 0,
//            "Black Sea": 0,
//            "Brasseries": 0,
//            "Brazilian": 0,
//            "Brazilian Empanadas": 0,
//            "Central Brazilian": 0,
//            "Northeastern Brazilian": 0,
//            "Northern Brazilian": 0,
//            "Rodizios": 0,
//            "Breakfast & Brunch": 0,
//            "Pancakes": 0,
//            "British": 0,
//            "Buffets": 0,
//            "Bulgarian": 0,
//            "Burgers": 0,
//            "Burmese": 0,
//            "Cafes": 0,
//            "Themed Cafes": 0,
//            "Cafeteria": 0,
//            "Cajun/Creole": 0,
//            "Cambodian": 0,
//            "Canadian (New)": 0,
//            "Canteen": 0,
//            "Caribbean": 0,
//            "Dominican": 0,
//            "Haitian": 0,
//            "Puerto Rican": 0,
//            "Trinidadian": 0,
//            "Catalan": 0,
//            "Cheesesteaks": 0,
//            "Chicken Shop": 0,
//            "Chicken Wings": 0,
//            "Chilean": 0,
//            "Chinese": 0,
//            "Cantonese": 0,
//            "Congee": 0,
//            "Dim Sum": 0,
//            "Fuzhou": 0,
//            "Hainan": 0,
//            "Hakka": 0,
//            "Henghwa": 0,
//            "Hokkien": 0,
//            "Hunan": 0,
//            "Pekinese": 0,
//            "Shanghainese": 0,
//            "Szechuan": 0,
//            "Teochew": 0,
//            "Comfort Food": 0,
//            "Corsican": 0,
//            "Creperies": 0,
//            "Cuban": 0,
//            "Curry Sausage": 0,
//            "Cypriot": 0,
//            "Czech": 0,
//            "Czech/Slovakian": 0,
//            "Danish": 0,
//            "Delis": 0,
//            "Diners": 0,
//            "Dinner Theater": 0,
//            "Dumplings": 0,
//            "Eastern European": 0,
//            "Eritrean": 0,
//            "Ethiopian": 0,
//            "Fast Food": 0,
//            "Filipino": 0,
//            "Fischbroetchen": 0,
//            "Fish & Chips": 0,
//            "Flatbread": 0,
//            "Fondue": 0,
//            "Food Court": 0,
//            "Food Stands": 0,
//            "Freiduria": 0,
//            "French": 0,
//            "Alsatian": 0,
//            "Auvergnat": 0,
//            "Berrichon": 0,
//            "Bourguignon": 0,
//            "Mauritius": 0,
//            "Nicoise": 0,
//            "Provencal": 0,
//            "French Southwest": 0,
//            "Galician": 0,
//            "Game Meat": 0,
//            "Gastropubs": 0,
//            "Georgian": 0,
//            "German": 0,
//            "Baden": 0,
//            "Eastern German": 0,
//            "Franconian": 0,
//            "Hessian": 0,
//            "Northern German": 0,
//            "Palatine": 0,
//            "Rhinelandian": 0,
//            "Giblets": 0,
//            "Gluten-Free": 0,
//            "Greek": 0,
//            "Guamanian": 0,
//            "Halal": 0,
//            "Hawaiian": 0,
//            "Heuriger": 0,
//            "Himalayan/Nepalese": 0,
//            "Honduran": 0,
//            "Hong Kong Style Cafe": 0,
//            "Hot Dogs": 0,
//            "Hot Pot": 0,
//            "Hungarian": 0,
//            "Iberian": 0,
//            "Indian": 0,
//            "Indonesian": 0,
//            "International": 0,
//            "Irish": 0,
//            "Island Pub": 0,
//            "Israeli": 0,
//            "Italian": 0,
//            "Abruzzese": 0,
//            "Altoatesine": 0,
//            "Apulian": 0,
//            "Calabrian": 0,
//            "Cucina Campana": 0,
//            "Emilian": 0,
//            "Friulan": 0,
//            "Ligurian": 0,
//            "Lumbard": 0,
//            "Napoletana": 0,
//            "Piemonte": 0,
//            "Roman": 0,
//            "Sardinian": 0,
//            "Sicilian": 0,
//            "Tuscan": 0,
//            "Venetian": 0,
//            "Japanese": 0,
//            "Blowfish": 0,
//            "Conveyor Belt Sushi": 0,
//            "Donburi": 0,
//            "Gyudon": 0,
//            "Oyakodon": 0,
//            "Hand Rolls": 0,
//            "Horumon": 0,
//            "Izakaya": 0,
//            "Japanese Curry": 0,
//            "Kaiseki": 0,
//            "Kushikatsu": 0,
//            "Oden": 0,
//            "Okinawan": 0,
//            "Okonomiyaki": 0,
//            "Onigiri": 0,
//            "Ramen": 0,
//            "Robatayaki": 0,
//            "Soba": 0,
//            "Sukiyaki": 0,
//            "Takoyaki": 0,
//            "Tempura": 0,
//            "Teppanyaki": 0,
//            "Tonkatsu": 0,
//            "Udon": 0,
//            "Unagi": 0,
//            "Western Style Japanese Food": 0,
//            "Yakiniku": 0,
//            "Yakitori": 0,
//            "Jewish": 0,
//            "Kebab": 0,
//            "Kopitiam": 0,
//            "Korean": 0,
//            "Kosher": 0,
//            "Kurdish": 0,
//            "Laos": 0,
//            "Laotian": 0,
//            "Latin American": 0,
//            "Colombian": 0,
//            "Salvadoran": 0,
//            "Venezuelan": 0,
//            "Live/Raw Food": 0,
//            "Lyonnais": 0,
//            "Malaysian": 0,
//            "Mamak": 0,
//            "Nyonya": 0,
//            "Meatballs": 0,
//            "Mediterranean": 0,
//            "Falafel": 0,
//            "Mexican": 0,
//            "Eastern Mexican": 0,
//            "Jaliscan": 0,
//            "Northern Mexican": 0,
//            "Oaxacan": 0,
//            "Pueblan": 0,
//            "Tacos": 0,
//            "Tamales": 0,
//            "Yucatan": 0,
//            "Middle Eastern": 0,
//            "Egyptian": 0,
//            "Lebanese": 0,
//            "Milk Bars": 0,
//            "Modern Australian": 0,
//            "Modern European": 0,
//            "Mongolian": 0,
//            "Moroccan": 0,
//            "New Mexican Cuisine": 0,
//            "New Zealand": 0,
//            "Nicaraguan": 0,
//            "Night Food": 0,
//            "Nikkei": 0,
//            "Noodles": 0,
//            "Norcinerie": 0,
//            "Open Sandwiches": 0,
//            "Oriental": 0,
//            "Pakistani": 0,
//            "Pan Asian": 0,
//            "Parent Cafes": 0,
//            "Parma": 0,
//            "Persian/Iranian": 0,
//            "Peruvian": 0,
//            "PF/Comercial": 0,
//            "Pita": 0,
//            "Pizza": 0,
//            "Polish": 0,
//            "Pierogis": 0,
//            "Polynesian": 0,
//            "Pop-Up Restaurants": 0,
//            "Portuguese": 0,
//            "Alentejo": 0,
//            "Algarve": 0,
//            "Azores": 0,
//            "Beira": 0,
//            "Fado Houses": 0,
//            "Madeira": 0,
//            "Minho": 0,
//            "Ribatejo": 0,
//            "Tras-os-Montes": 0,
//            "Potatoes": 0,
//            "Poutineries": 0,
//            "Pub Food": 0,
//            "Rice": 0,
//            "Romanian": 0,
//            "Rotisserie Chicken": 0,
//            "Russian": 0,
//            "Salad": 0,
//            "Sandwiches": 0,
//            "Scandinavian": 0,
//            "Schnitzel": 0,
//            "Scottish": 0,
//            "Seafood": 0,
//            "Serbo Croatian": 0,
//            "Signature Cuisine": 0,
//            "Singaporean": 0,
//            "Slovakian": 0,
//            "Somali": 0,
//            "Soul Food": 0,
//            "Soup": 0,
//            "Southern": 0,
//            "Spanish": 0,
//            "Arroceria/Paella": 0,
//            "Sri Lankan": 0,
//            "Steakhouses": 0,
//            "Supper Clubs": 0,
//            "Sushi Bars": 0,
//            "Swabian": 0,
//            "Swedish": 0,
//            "Swiss Food": 0,
//            "Syrian": 0,
//            "Tabernas": 0,
//            "Taiwanese": 0,
//            "Tapas Bars": 0,
//            "Tapas/Small Plates": 0,
//            "Tavola Calda": 0,
//            "Tex-Mex": 0,
//            "Thai": 0,
//            "Traditional Norwegian": 0,
//            "Traditional Swedish": 0,
//            "Trattorie": 0,
//            "Turkish": 0,
//            "Chee Kufta": 0,
//            "Gozleme": 0,
//            "Homemade Food": 0,
//            "Lahmacun": 0,
//            "Ottoman Cuisine": 0,
//            "Turkish Ravioli": 0,
//            "Ukrainian": 0,
//            "Uzbek": 0,
//            "Vegan": 0,
//            "Vegetarian": 0,
//            "Venison": 0,
//            "Vietnamese": 0,
//            "Waffles": 0,
//            "Wok": 0,
//            "Wraps": 0,
//            "Yugoslav": 0
//        ]
//        case .shopping: [
//            "Adult": 0,
//            "Antiques": 0,
//            "Art Galleries": 0,
//            "Arts & Crafts": 0,
//            "Art Supplies": 0,
//            "Ateliers": 0,
//            "Cards & Stationery": 0,
//            "Cooking Classes": 0,
//            "Costumes": 0,
//            "Embroidery & Crochet": 0,
//            "Fabric Stores": 0,
//            "Framing": 0,
//            "Paint-Your-Own Pottery": 0,
//            "Auction Houses": 0,
//            "Baby Gear & Furniture": 0,
//            "Battery Stores": 0,
//            "Bespoke Clothing": 0,
//            "Books, Mags, Music & Video": 0,
//            "Bookstores": 0,
//            "Comic Books": 0,
//            "Music & DVDs": 0,
//            "Newspapers & Magazines": 0,
//            "Video Game Stores": 0,
//            "Videos & Video Game Rental": 0,
//            "Vinyl Records": 0,
//            "Brewing Supplies": 0,
//            "Bridal": 0,
//            "Cannabis Dispensaries": 0,
//            "Chinese Bazaar": 0,
//            "Computers": 0,
//            "Concept Shops": 0,
//            "Cosmetics & Beauty Supply": 0,
//            "Customized Merchandise": 0,
//            "Diamond Buyers": 0,
//            "Discount Store": 0,
//            "Drones": 0,
//            "Drugstores": 0,
//            "Duty-Free Shops": 0,
//            "Electronics": 0,
//            "Eyewear & Opticians": 0,
//            "Sunglasses": 0,
//            "Farming Equipment": 0,
//            "Fashion": 0,
//            "Accessories": 0,
//            "Ceremonial Clothing": 0,
//            "Children’s Clothing": 0,
//            "Clothing Rental": 0,
//            "Department Stores": 0,
//            "Formal Wear": 0,
//            "Fur Clothing": 0,
//            "Hats": 0,
//            "Kimonos": 0,
//            "Leather Goods": 0,
//            "Lingerie": 0,
//            "Maternity Wear": 0,
//            "Men’s Clothing": 0,
//            "Plus Size Fashion": 0,
//            "Shoe Stores": 0,
//            "Sleepwear": 0,
//            "Sports Wear": 0,
//            "Dance Wear": 0,
//            "Stockings": 0,
//            "Surf Shop": 0,
//            "Swimwear": 0,
//            "Traditional Clothing": 0,
//            "Used, Vintage & Consignment": 0,
//            "Women’s Clothing": 0,
//            "Fireworks": 0,
//            "Fitness/Exercise Equipment": 0,
//            "Flea Markets": 0,
//            "Flowers & Gifts": 0,
//            "Florists": 0,
//            "Gift Shops": 0,
//            "Gemstones & Minerals": 0,
//            "Gold Buyers": 0,
//            "Guns & Ammo": 0,
//            "Head Shops": 0,
//            "High Fidelity Audio Equipment": 0,
//            "Hobby Shops": 0,
//            "Home & Garden": 0,
//            "Appliances": 0,
//            "Candle Stores": 0,
//            "Christmas Trees": 0,
//            "Furniture Stores": 0,
//            "Grilling Equipment": 0,
//            "Hardware Stores": 0,
//            "Holiday Decorations": 0,
//            "Home Decor": 0,
//            "Hot Tub & Pool": 0,
//            "Kitchen & Bath": 0,
//            "Kitchen Supplies": 0,
//            "Lighting Stores": 0,
//            "Linens": 0,
//            "Materiale elettrico": 0,
//            "Mattresses": 0,
//            "Nurseries & Gardening": 0,
//            "Hydroponics": 0,
//            "Outdoor Furniture Stores": 0,
//            "Paint Stores": 0,
//            "Playsets": 0,
//            "Pumpkin Patches": 0,
//            "Rugs": 0,
//            "Sheds & Outdoor Storage": 0,
//            "Tableware": 0,
//            "Horse Equipment Shops": 0,
//            "Jewelry": 0,
//            "Kiosk": 0,
//            "Knitting Supplies": 0,
//            "Livestock Feed & Supply": 0,
//            "Luggage": 0,
//            "Market Stalls": 0,
//            "Medical Supplies": 0,
//            "Military Surplus": 0,
//            "Mobile Phone Accessories": 0,
//            "Mobile Phones": 0,
//            "Motorcycle Gear": 0,
//            "Musical Instruments & Teachers": 0,
//            "Office Equipment": 0,
//            "Outlet Stores": 0,
//            "Packing Supplies": 0,
//            "Pawn Shops": 0,
//            "Perfume": 0,
//            "Personal Shopping": 0,
//            "Photography Stores & Services": 0,
//            "Pool & Billiards": 0,
//            "Pop-up Shops": 0,
//            "Props": 0,
//            "Public Markets": 0,
//            "Religious Items": 0,
//            "Safe Stores": 0,
//            "Safety Equipment": 0,
//            "Scandinavian Design": 0,
//            "Shopping Centers": 0,
//            "Shopping Passages": 0,
//            "Souvenir Shops": 0,
//            "Spiritual Shop": 0,
//            "Sporting Goods": 0,
//            "Bikes": 0,
//            "Dive Shops": 0,
//            "Golf Equipment": 0,
//            "Hockey Equipment": 0,
//            "Hunting & Fishing Supplies": 0,
//            "Outdoor Gear": 0,
//            "Skate Shops": 0,
//            "Ski & Snowboard Shops": 0,
//            "Tabletop Games": 0,
//            "Teacher Supplies": 0,
//            "Thrift Stores": 0,
//            "Tickets": 0,
//            "Tobacco Shops": 0,
//            "Toy Stores": 0,
//            "Trophy Shops": 0,
//            "Uniforms": 0,
//            "Used Bookstore": 0,
//            "Vape Shops": 0,
//            "Vitamins & Supplements": 0,
//            "Watches": 0,
//            "Wholesale Stores": 0,
//            "Wigs": 0
//        ]
//        }
//    }
    
}

@Model
class YelpCategory {
    var name: String
    var subCategories: [SubCategory] = []
    
    init(name: String, subCategories: [SubCategory]) {
        self.name = name
        self.subCategories = subCategories
    }
}

@Model
class SubCategory {
    var name: String
    var count: Int
    
    init(name: String, count: Int = 0) {
        self.name = name
        self.count = count
    }
}

@Model
class CategoryManager: ObservableObject {
    
    var categories: [YelpCategory]
        
    init() {
        categories = [
            YelpCategory(name: "Active", subCategories: [
                SubCategory(name: "Airsoft"),
                SubCategory(name: "Amateur Sports Teams"),
                SubCategory(name: "Amusement Parks"),
                SubCategory(name: "Aquariums"),
                SubCategory(name: "Archery"),
                SubCategory(name: "ATV Rentals/Tours"),
                SubCategory(name: "Axe Throwing"),
                SubCategory(name: "Badminton"),
                SubCategory(name: "Baseball Fields"),
                SubCategory(name: "Basketball Courts"),
                SubCategory(name: "Bathing Area"),
                SubCategory(name: "Batting Cages"),
                SubCategory(name: "Beach Equipment Rentals"),
                SubCategory(name: "Beach Volleyball"),
                SubCategory(name: "Beaches"),
                SubCategory(name: "Bicycle Paths"),
                SubCategory(name: "Bike Parking"),
                SubCategory(name: "Bike Rentals"),
                SubCategory(name: "Boating"),
                SubCategory(name: "Bobsledding"),
                SubCategory(name: "Bocce Ball"),
                SubCategory(name: "Bowling"),
                SubCategory(name: "Bubble Soccer"),
                SubCategory(name: "Bungee Jumping"),
                SubCategory(name: "Canyoneering"),
                SubCategory(name: "Carousels"),
                SubCategory(name: "Challenge Courses"),
                SubCategory(name: "Climbing"),
                SubCategory(name: "Cycling Classes"),
                SubCategory(name: "Dart Arenas"),
                SubCategory(name: "Disc Golf"),
                SubCategory(name: "Diving"),
                SubCategory(name: "Free Diving"),
                SubCategory(name: "Scuba Diving"),
                SubCategory(name: "Escape Games"),
                SubCategory(name: "Fencing Clubs"),
                SubCategory(name: "Fishing"),
                SubCategory(name: "Fitness & Instruction"),
                SubCategory(name: "Aerial Fitness"),
                SubCategory(name: "Barre Classes"),
                SubCategory(name: "Boxing"),
                SubCategory(name: "Cardio Classes"),
                SubCategory(name: "Dance Studios"),
                SubCategory(name: "Golf Lessons"),
                SubCategory(name: "Gyms"),
                SubCategory(name: "Circuit Training Gyms"),
                SubCategory(name: "Interval Training Gyms"),
                SubCategory(name: "Martial Arts"),
                SubCategory(name: "Brazilian Jiu-jitsu"),
                SubCategory(name: "Chinese Martial Arts"),
                SubCategory(name: "Karate"),
                SubCategory(name: "Kickboxing"),
                SubCategory(name: "Muay Thai"),
                SubCategory(name: "Taekwondo"),
                SubCategory(name: "Meditation Centers"),
                SubCategory(name: "Pilates"),
                SubCategory(name: "Qi Gong"),
                SubCategory(name: "Self-defense Classes"),
                SubCategory(name: "Swimming Lessons/Schools"),
                SubCategory(name: "Tai Chi"),
                SubCategory(name: "Trainers"),
                SubCategory(name: "Yoga"),
                SubCategory(name: "Flyboarding"),
                SubCategory(name: "Gliding"),
                SubCategory(name: "Go Karts"),
                SubCategory(name: "Golf"),
                SubCategory(name: "Gun/Rifle Ranges"),
                SubCategory(name: "Gymnastics"),
                SubCategory(name: "Handball"),
                SubCategory(name: "Hang Gliding"),
                SubCategory(name: "Hiking"),
                SubCategory(name: "Horse Racing"),
                SubCategory(name: "Horseback Riding"),
                SubCategory(name: "Hot Air Balloons"),
                SubCategory(name: "Indoor Playcentre"),
                SubCategory(name: "Jet Skis"),
                SubCategory(name: "Kids Activities"),
                SubCategory(name: "Kiteboarding"),
                SubCategory(name: "Lakes"),
                SubCategory(name: "Laser Tag"),
                SubCategory(name: "Lawn Bowling"),
                SubCategory(name: "Mini Golf"),
                SubCategory(name: "Mountain Biking"),
                SubCategory(name: "Nudist"),
                SubCategory(name: "Paddleboarding"),
                SubCategory(name: "Paintball"),
                SubCategory(name: "Paragliding"),
                SubCategory(name: "Parasailing"),
                SubCategory(name: "Parks"),
                SubCategory(name: "Dog Parks"),
                SubCategory(name: "Skate Parks"),
                SubCategory(name: "Pickleball"),
                SubCategory(name: "Playgrounds"),
                SubCategory(name: "Public Plazas"),
                SubCategory(name: "Races & Competitions"),
                SubCategory(name: "Racing Experience"),
                SubCategory(name: "Rafting/Kayaking"),
                SubCategory(name: "Recreation Centers"),
                SubCategory(name: "Rock Climbing"),
                SubCategory(name: "Sailing"),
                SubCategory(name: "Scavenger Hunts"),
                SubCategory(name: "Scooter Rentals"),
                SubCategory(name: "Senior Centers"),
                SubCategory(name: "Skating Rinks"),
                SubCategory(name: "Skiing"),
                SubCategory(name: "Skydiving"),
                SubCategory(name: "Sledding"),
                SubCategory(name: "Snorkeling"),
                SubCategory(name: "Soccer"),
                SubCategory(name: "Sport Equipment Hire"),
                SubCategory(name: "Sports Clubs"),
                SubCategory(name: "Squash"),
                SubCategory(name: "Summer Camps"),
                SubCategory(name: "Surf Lifesaving"),
                SubCategory(name: "Surfing"),
                SubCategory(name: "Swimming Pools"),
                SubCategory(name: "Tennis"),
                SubCategory(name: "Trampoline Parks"),
                SubCategory(name: "Tubing"),
                SubCategory(name: "Volleyball"),
                SubCategory(name: "Water Parks"),
                SubCategory(name: "Wildlife Hunting Ranges"),
                SubCategory(name: "Ziplining"),
                SubCategory(name: "Zoos"),
                SubCategory(name: "Petting Zoos"),
                SubCategory(name: "Zorbing")
            ]),
            YelpCategory(name: "Night", subCategories: [
                SubCategory(name: "Adult Entertainment"),
                SubCategory(name: "Strip Clubs"),
                SubCategory(name: "Striptease Dancers"),
                SubCategory(name: "Bar Crawl"),
                SubCategory(name: "Bars"),
                SubCategory(name: "Airport Lounges"),
                SubCategory(name: "Beer Bar"),
                SubCategory(name: "Champagne Bars"),
                SubCategory(name: "Cigar Bars"),
                SubCategory(name: "Cocktail Bars"),
                SubCategory(name: "Dive Bars"),
                SubCategory(name: "Drive-Thru Bars"),
                SubCategory(name: "Gay Bars"),
                SubCategory(name: "Hookah Bars"),
                SubCategory(name: "Irish Pub"),
                SubCategory(name: "Lounges"),
                SubCategory(name: "Pubs"),
                SubCategory(name: "Speakeasies"),
                SubCategory(name: "Sports Bars"),
                SubCategory(name: "Tiki Bars"),
                SubCategory(name: "Vermouth Bars"),
                SubCategory(name: "Whiskey Bars"),
                SubCategory(name: "Wine Bars"),
                SubCategory(name: "Beer Gardens"),
                SubCategory(name: "Club Crawl"),
                SubCategory(name: "Comedy Clubs"),
                SubCategory(name: "Country Dance Halls"),
                SubCategory(name: "Dance Clubs"),
                SubCategory(name: "Jazz & Blues"),
                SubCategory(name: "Karaoke"),
                SubCategory(name: "Music Venues"),
                SubCategory(name: "Piano Bars"),
                SubCategory(name: "Pool Halls")
            ]),
            YelpCategory(name: "Food", subCategories: [
                SubCategory(name: "Afghan"),
                SubCategory(name: "African"),
                SubCategory(name: "Senegalese"),
                SubCategory(name: "South African"),
                SubCategory(name: "American (New)"),
                SubCategory(name: "American (Traditional)"),
                SubCategory(name: "Andalusian"),
                SubCategory(name: "Arabian"),
                SubCategory(name: "Arab Pizza"),
                SubCategory(name: "Argentine"),
                SubCategory(name: "Armenian"),
                SubCategory(name: "Asian Fusion"),
                SubCategory(name: "Asturian"),
                SubCategory(name: "Australian"),
                SubCategory(name: "Austrian"),
                SubCategory(name: "Baguettes"),
                SubCategory(name: "Bangladeshi"),
                SubCategory(name: "Barbeque"),
                SubCategory(name: "Basque"),
                SubCategory(name: "Bavarian"),
                SubCategory(name: "Beer Garden"),
                SubCategory(name: "Beer Hall"),
                SubCategory(name: "Beisl"),
                SubCategory(name: "Belgian"),
                SubCategory(name: "Flemish"),
                SubCategory(name: "Bistros"),
                SubCategory(name: "Black Sea"),
                SubCategory(name: "Brasseries"),
                SubCategory(name: "Brazilian"),
                SubCategory(name: "Brazilian Empanadas"),
                SubCategory(name: "Central Brazilian"),
                SubCategory(name: "Northeastern Brazilian"),
                SubCategory(name: "Northern Brazilian"),
                SubCategory(name: "Rodizios"),
                SubCategory(name: "Breakfast & Brunch"),
                SubCategory(name: "Pancakes"),
                SubCategory(name: "British"),
                SubCategory(name: "Buffets"),
                SubCategory(name: "Bulgarian"),
                SubCategory(name: "Burgers"),
                SubCategory(name: "Burmese"),
                SubCategory(name: "Cafes"),
                SubCategory(name: "Themed Cafes"),
                SubCategory(name: "Cafeteria"),
                SubCategory(name: "Cajun/Creole"),
                SubCategory(name: "Cambodian"),
                SubCategory(name: "Canadian (New)"),
                SubCategory(name: "Canteen"),
                SubCategory(name: "Caribbean"),
                SubCategory(name: "Dominican"),
                SubCategory(name: "Haitian"),
                SubCategory(name: "Puerto Rican"),
                SubCategory(name: "Trinidadian"),
                SubCategory(name: "Catalan"),
                SubCategory(name: "Cheesesteaks"),
                SubCategory(name: "Chicken Shop"),
                SubCategory(name: "Chicken Wings"),
                SubCategory(name: "Chilean"),
                SubCategory(name: "Chinese"),
                SubCategory(name: "Cantonese"),
                SubCategory(name: "Congee"),
                SubCategory(name: "Dim Sum"),
                SubCategory(name: "Fuzhou"),
                SubCategory(name: "Hainan"),
                SubCategory(name: "Hakka"),
                SubCategory(name: "Henghwa"),
                SubCategory(name: "Hokkien"),
                SubCategory(name: "Hunan"),
                SubCategory(name: "Pekinese"),
                SubCategory(name: "Shanghainese"),
                SubCategory(name: "Szechuan"),
                SubCategory(name: "Teochew"),
                SubCategory(name: "Comfort Food"),
                SubCategory(name: "Corsican"),
                SubCategory(name: "Creperies"),
                SubCategory(name: "Cuban"),
                SubCategory(name: "Curry Sausage"),
                SubCategory(name: "Cypriot"),
                SubCategory(name: "Czech"),
                SubCategory(name: "Czech/Slovakian"),
                SubCategory(name: "Danish"),
                SubCategory(name: "Delis"),
                SubCategory(name: "Diners"),
                SubCategory(name: "Dinner Theater"),
                SubCategory(name: "Dumplings"),
                SubCategory(name: "Eastern European"),
                SubCategory(name: "Eritrean"),
                SubCategory(name: "Ethiopian"),
                SubCategory(name: "Fast Food"),
                SubCategory(name: "Filipino"),
                SubCategory(name: "Fischbroetchen"),
                SubCategory(name: "Fish & Chips"),
                SubCategory(name: "Flatbread"),
                SubCategory(name: "Fondue"),
                SubCategory(name: "Food Court"),
                SubCategory(name: "Food Stands"),
                SubCategory(name: "Freiduria"),
                SubCategory(name: "French"),
                SubCategory(name: "Alsatian"),
                SubCategory(name: "Auvergnat"),
                SubCategory(name: "Berrichon"),
                SubCategory(name: "Bourguignon"),
                SubCategory(name: "Mauritius"),
                SubCategory(name: "Nicoise"),
                SubCategory(name: "Provencal"),
                SubCategory(name: "French Southwest"),
                SubCategory(name: "Galician"),
                SubCategory(name: "Game Meat"),
                SubCategory(name: "Gastropubs"),
                SubCategory(name: "Georgian"),
                SubCategory(name: "German"),
                SubCategory(name: "Baden"),
                SubCategory(name: "Eastern German"),
                SubCategory(name: "Franconian"),
                SubCategory(name: "Hessian"),
                SubCategory(name: "Northern German"),
                SubCategory(name: "Palatine"),
                SubCategory(name: "Rhinelandian"),
                SubCategory(name: "Giblets"),
                SubCategory(name: "Gluten-Free"),
                SubCategory(name: "Greek"),
                SubCategory(name: "Guamanian"),
                SubCategory(name: "Halal"),
                SubCategory(name: "Hawaiian"),
                SubCategory(name: "Heuriger"),
                SubCategory(name: "Himalayan/Nepalese"),
                SubCategory(name: "Honduran"),
                SubCategory(name: "Hong Kong Style Cafe"),
                SubCategory(name: "Hot Dogs"),
                SubCategory(name: "Hot Pot"),
                SubCategory(name: "Hungarian"),
                SubCategory(name: "Iberian"),
                SubCategory(name: "Indian"),
                SubCategory(name: "Indonesian"),
                SubCategory(name: "International"),
                SubCategory(name: "Irish"),
                SubCategory(name: "Island Pub"),
                SubCategory(name: "Israeli"),
                SubCategory(name: "Italian"),
                SubCategory(name: "Abruzzese"),
                SubCategory(name: "Altoatesine"),
                SubCategory(name: "Apulian"),
                SubCategory(name: "Calabrian"),
                SubCategory(name: "Cucina Campana"),
                SubCategory(name: "Emilian"),
                SubCategory(name: "Friulan"),
                SubCategory(name: "Ligurian"),
                SubCategory(name: "Lumbard"),
                SubCategory(name: "Napoletana"),
                SubCategory(name: "Piemonte"),
                SubCategory(name: "Roman"),
                SubCategory(name: "Sardinian"),
                SubCategory(name: "Sicilian"),
                SubCategory(name: "Tuscan"),
                SubCategory(name: "Venetian"),
                SubCategory(name: "Japanese"),
                SubCategory(name: "Blowfish"),
                SubCategory(name: "Conveyor Belt Sushi"),
                SubCategory(name: "Donburi"),
                SubCategory(name: "Gyudon"),
                SubCategory(name: "Oyakodon"),
                SubCategory(name: "Hand Rolls"),
                SubCategory(name: "Horumon"),
                SubCategory(name: "Izakaya"),
                SubCategory(name: "Japanese Curry"),
                SubCategory(name: "Kaiseki"),
                SubCategory(name: "Kushikatsu"),
                SubCategory(name: "Oden"),
                SubCategory(name: "Okinawan"),
                SubCategory(name: "Okonomiyaki"),
                SubCategory(name: "Onigiri"),
                SubCategory(name: "Ramen"),
                SubCategory(name: "Robatayaki"),
                SubCategory(name: "Soba"),
                SubCategory(name: "Sukiyaki"),
                SubCategory(name: "Takoyaki"),
                SubCategory(name: "Tempura"),
                SubCategory(name: "Teppanyaki"),
                SubCategory(name: "Tonkatsu"),
                SubCategory(name: "Udon"),
                SubCategory(name: "Unagi"),
                SubCategory(name: "Western Style Japanese Food"),
                SubCategory(name: "Yakiniku"),
                SubCategory(name: "Yakitori"),
                SubCategory(name: "Jewish"),
                SubCategory(name: "Kebab"),
                SubCategory(name: "Kopitiam"),
                SubCategory(name: "Korean"),
                SubCategory(name: "Kosher"),
                SubCategory(name: "Kurdish"),
                SubCategory(name: "Laos"),
                SubCategory(name: "Laotian"),
                SubCategory(name: "Latin American"),
                SubCategory(name: "Colombian"),
                SubCategory(name: "Salvadoran"),
                SubCategory(name: "Venezuelan"),
                SubCategory(name: "Live/Raw Food"),
                SubCategory(name: "Lyonnais"),
                SubCategory(name: "Malaysian"),
                SubCategory(name: "Mamak"),
                SubCategory(name: "Nyonya"),
                SubCategory(name: "Meatballs"),
                SubCategory(name: "Mediterranean"),
                SubCategory(name: "Falafel"),
                SubCategory(name: "Mexican"),
                SubCategory(name: "Eastern Mexican"),
                SubCategory(name: "Jaliscan"),
                SubCategory(name: "Northern Mexican"),
                SubCategory(name: "Oaxacan"),
                SubCategory(name: "Pueblan"),
                SubCategory(name: "Tacos"),
                SubCategory(name: "Tamales"),
                SubCategory(name: "Yucatan"),
                SubCategory(name: "Middle Eastern"),
                SubCategory(name: "Egyptian"),
                SubCategory(name: "Lebanese"),
                SubCategory(name: "Milk Bars"),
                SubCategory(name: "Modern Australian"),
                SubCategory(name: "Modern European"),
                SubCategory(name: "Mongolian"),
                SubCategory(name: "Moroccan"),
                SubCategory(name: "New Mexican Cuisine"),
                SubCategory(name: "New Zealand"),
                SubCategory(name: "Nicaraguan"),
                SubCategory(name: "Night Food"),
                SubCategory(name: "Nikkei"),
                SubCategory(name: "Noodles"),
                SubCategory(name: "Norcinerie"),
                SubCategory(name: "Open Sandwiches"),
                SubCategory(name: "Oriental"),
                SubCategory(name: "Pakistani"),
                SubCategory(name: "Pan Asian"),
                SubCategory(name: "Parent Cafes"),
                SubCategory(name: "Parma"),
                SubCategory(name: "Peruvian"),
                SubCategory(name: "PF/Comercial"),
                SubCategory(name: "Pita"),
                SubCategory(name: "Pizza"),
                SubCategory(name: "Polish"),
                SubCategory(name: "Pierogis"),
                SubCategory(name: "Polynesian"),
                SubCategory(name: "Pop-Up Restaurants"),
                SubCategory(name: "Portuguese"),
                SubCategory(name: "Alentejo"),
                SubCategory(name: "Algarve"),
                SubCategory(name: "Azores"),
                SubCategory(name: "Beira"),
                SubCategory(name: "Fado Houses"),
                SubCategory(name: "Madeira"),
                SubCategory(name: "Minho"),
                SubCategory(name: "Ribatejo"),
                SubCategory(name: "Tras-os-Montes"),
                SubCategory(name: "Potatoes"),
                SubCategory(name: "Poutineries"),
                SubCategory(name: "Pub Food"),
                SubCategory(name: "Rice"),
                SubCategory(name: "Romanian"),
                SubCategory(name: "Rotisserie Chicken"),
                SubCategory(name: "Russian"),
                SubCategory(name: "Salad"),
                SubCategory(name: "Sandwiches"),
                SubCategory(name: "Scandinavian"),
                SubCategory(name: "Schnitzel"),
                SubCategory(name: "Scottish"),
                SubCategory(name: "Seafood"),
                SubCategory(name: "Serbo Croatian"),
                SubCategory(name: "Signature Cuisine"),
                SubCategory(name: "Singaporean"),
                SubCategory(name: "Slovakian"),
                SubCategory(name: "Somali"),
                SubCategory(name: "Soul Food"),
                SubCategory(name: "Soup"),
                SubCategory(name: "Southern"),
                SubCategory(name: "Spanish"),
                SubCategory(name: "Arroceria/Paella"),
                SubCategory(name: "Sri Lankan"),
                SubCategory(name: "Steakhouses"),
                SubCategory(name: "Supper Clubs"),
                SubCategory(name: "Sushi Bars"),
                SubCategory(name: "Swabian"),
                SubCategory(name: "Swedish"),
                SubCategory(name: "Swiss Food"),
                SubCategory(name: "Syrian"),
                SubCategory(name: "Tabernas"),
                SubCategory(name: "Taiwanese"),
                SubCategory(name: "Tapas Bars"),
                SubCategory(name: "Tapas/Small Plates"),
                SubCategory(name: "Tavola Calda"),
                SubCategory(name: "Tex-Mex"),
                SubCategory(name: "Thai"),
                SubCategory(name: "Traditional Norwegian"),
                SubCategory(name: "Traditional Swedish"),
                SubCategory(name: "Trattorie"),
                SubCategory(name: "Turkish"),
                SubCategory(name: "Chee Kufta"),
                SubCategory(name: "Gozleme"),
                SubCategory(name: "Homemade Food"),
                SubCategory(name: "Lahmacun"),
                SubCategory(name: "Ottoman Cuisine"),
                SubCategory(name: "Turkish Ravioli"),
                SubCategory(name: "Ukrainian"),
                SubCategory(name: "Uzbek"),
                SubCategory(name: "Vegan"),
                SubCategory(name: "Vegetarian"),
                SubCategory(name: "Venison"),
                SubCategory(name: "Vietnamese"),
                SubCategory(name: "Waffles"),
                SubCategory(name: "Wok"),
                SubCategory(name: "Wraps"),
                SubCategory(name: "Yugoslav")
            ]),
            YelpCategory(name: "Relax", subCategories: [
                SubCategory(name: "Acne Treatment"),
                SubCategory(name: "Barbers"),
                SubCategory(name: "Cosmetics & Beauty Supply"),
                SubCategory(name: "Day Spas"),
                SubCategory(name: "Erotic Massage"),
                SubCategory(name: "Eyebrow Services"),
                SubCategory(name: "Eyelash Service"),
                SubCategory(name: "Foot Care"),
                SubCategory(name: "Hair Extensions"),
                SubCategory(name: "Hair Loss Centers"),
                SubCategory(name: "Hair Removal"),
                SubCategory(name: "Laser Hair Removal"),
                SubCategory(name: "Sugaring"),
                SubCategory(name: "Threading Services"),
                SubCategory(name: "Waxing"),
                SubCategory(name: "Hair Salons"),
                SubCategory(name: "Blow Dry/Out Services"),
                SubCategory(name: "Hair Stylists"),
                SubCategory(name: "Kids Hair Salons"),
                SubCategory(name: "Men’s Hair Salons"),
                SubCategory(name: "Hot Springs"),
                SubCategory(name: "Makeup Artists"),
                SubCategory(name: "Massage"),
                SubCategory(name: "Medical Spas"),
                SubCategory(name: "Nail Salons"),
                SubCategory(name: "Nail Technicians"),
                SubCategory(name: "Perfume"),
                SubCategory(name: "Permanent Makeup"),
                SubCategory(name: "Piercing"),
                SubCategory(name: "Skin Care"),
                SubCategory(name: "Estheticians"),
                SubCategory(name: "Tanning"),
                SubCategory(name: "Spray Tanning"),
                SubCategory(name: "Tanning Beds"),
                SubCategory(name: "Tattoo"),
                SubCategory(name: "Teeth Whitening")
            ]),
            YelpCategory(name: "Entertainment", subCategories: [
                SubCategory(name: "Arcades"),
                SubCategory(name: "Art Galleries"),
                SubCategory(name: "Bingo Halls"),
                SubCategory(name: "Botanical Gardens"),
                SubCategory(name: "Cabaret"),
                SubCategory(name: "Casinos"),
                SubCategory(name: "Cinema"),
                SubCategory(name: "Drive-In Theater"),
                SubCategory(name: "Outdoor Movies"),
                SubCategory(name: "Country Clubs"),
                SubCategory(name: "Cultural Center"),
                SubCategory(name: "Entertainment"),
                SubCategory(name: "Farms"),
                SubCategory(name: "Attraction Farms"),
                SubCategory(name: "Pick Your Own Farms"),
                SubCategory(name: "Ranches"),
                SubCategory(name: "Festivals"),
                SubCategory(name: "Haunted Houses"),
                SubCategory(name: "Jazz & Blues"),
                SubCategory(name: "LAN Centers"),
                SubCategory(name: "Makerspaces"),
                SubCategory(name: "Museums"),
                SubCategory(name: "Art Museums"),
                SubCategory(name: "Children’s Museums"),
                SubCategory(name: "Music Venues"),
                SubCategory(name: "Observatories"),
                SubCategory(name: "Opera & Ballet"),
                SubCategory(name: "Paint & Sip"),
                SubCategory(name: "Performing Arts"),
                SubCategory(name: "Planetarium"),
                SubCategory(name: "Professional Sports Teams"),
                SubCategory(name: "Race Tracks"),
                SubCategory(name: "Rodeo"),
                SubCategory(name: "Social Clubs"),
                SubCategory(name: "Veterans Organizations"),
                SubCategory(name: "Sports Betting"),
                SubCategory(name: "Stadiums & Arenas"),
                SubCategory(name: "Studio Taping"),
                SubCategory(name: "Supernatural Readings"),
                SubCategory(name: "Astrologers"),
                SubCategory(name: "Mystics"),
                SubCategory(name: "Psychic Mediums"),
                SubCategory(name: "Psychics"),
                SubCategory(name: "Tablao Flamenco"),
                SubCategory(name: "Ticket Sales"),
                SubCategory(name: "Virtual Reality Centers"),
                SubCategory(name: "Wineries"),
                SubCategory(name: "Wine Tasting Room")
            ]),
            YelpCategory(name: "Local", subCategories: [
                SubCategory(name: "Parklets"),
                SubCategory(name: "Public Art"),
                SubCategory(name: "Unofficial Yelp Events"),
                SubCategory(name: "Yelp Events")
            ])
        ]
    }
    
    func incrementSubCategory(categoryName: String, subCategoryName: String) {
        guard let categoryIndex = categories.firstIndex(where: { $0.name == categoryName }) else { return }
        guard let subCategoryIndex = categories[categoryIndex].subCategories.firstIndex(where: { $0.name == subCategoryName }) else { return }
        
        categories[categoryIndex].subCategories[subCategoryIndex].count += 1
    }
    
//    func findMaxCategory(categoryName: String, subCategoryName: String) -> String {
//
//    }
    
}

struct RandomCategory {
    let activities : [String] = ["airsoft", "amateursportsteams", "amusementparks", "aquariums", "archery", "atvrentals/tours", "axethrowing", "badminton", "baseballfields", "basketballcourts", "bathingarea", "battingcages", "beachvolleyball", "beaches", "bicyclepaths", "bikeparking", "boating", "bobsledding", "bocceball", "bowling", "bubblesoccer", "bungeejumping", "canyoneering", "challengecourses", "climbing", "cyclingclasses", "dartarenas", "discgolf", "diving", "freediving", "scubadiving", "escapegames", "fencingclubs", "fishing", "fitness&instruction", "aerialfitness", "barreclasses", "boxing", "cardioclasses", "dancestudios", "golflessons", "gyms", "circuittraininggyms", "intervaltraininggyms", "martialarts", "brazilianjiu-jitsu", "chinesemartialarts", "karate", "kickboxing", "muaythai", "taekwondo", "meditationcenters", "pilates", "qigong", "self-defenseclasses", "swimminglessons/schools", "taichi", "trainers", "yoga", "flyboarding", "gliding", "gokarts", "golf", "gun/rifleranges", "gymnastics", "handball", "hanggliding", "hiking", "horseracing", "horsebackriding", "hotairballoons", "indoorplaycentre", "jetskis", "kiteboarding", "lakes", "lasertag", "lawnbowling", "minigolf", "mountainbiking", "nudist", "paddleboarding", "paintball", "paragliding", "parasailing", "parks", "dogparks", "skateparks", "pickleball", "playgrounds", "publicplazas", "races&competitions", "racingexperience", "rafting/kayaking", "recreationcenters", "rockclimbing", "sailing", "scavengerhunts", "scooterrentals", "skatingrinks", "skiing", "skydiving", "sledding", "snorkeling", "soccer", "sportsclubs", "surfing", "swimmingpools", "tennis", "trampolineparks", "tubing", "volleyball", "waterparks", "wildlifehuntingranges", "ziplining", "zoos", "pettingzoos", "zorbing","arcades", "artgalleries", "bingohalls", "cabaret", "casinos", "cinema", "drive-intheater", "outdoormovies", "countryclubs", "culturalcenter", "entertainment", "farms", "attractionfarms", "ranches", "festivals", "hauntedhouses", "jazz&blues", "lancenters", "makerspaces", "museums", "artmuseums", "musicvenues", "observatories", "opera&ballet", "paint&sip", "performingarts", "planetarium", "professionalsportsteams", "racetracks", "rodeo", "socialclubs", "veteransorganizations", "sportsbetting", "stadiums&arenas", "studiotaping", "supernaturalreadings", "astrologers", "mystics", "psychicmediums", "psychics", "tablaoflamenco", "ticketsales", "virtualrealitycenters", "wineries", "winetastingroom","acnetreatment", "barbers", "cosmetics&beautysupply", "dayspas", "eroticmassage", "eyebrowservices", "eyelashservice", "footcare", "hairextensions", "hairlosscenters", "hairremoval", "laserhairremoval", "sugaring", "threadingservices", "waxing", "hairsalons", "blowdry/outservices", "hairextensions", "hairstylists", "men’shairsalons", "hotsprings", "makeupartists", "massage", "medicalspas", "nailsalons", "nailtechnicians", "perfume", "permanentmakeup", "piercing", "skincare", "estheticians", "tanning", "spraytanning", "tanningbeds", "tattoo","acaibowls", "backshop", "bagels", "bakeries", "beer,wine&spirits", "bento", "beveragestore", "breweries", "brewpubs", "bubbletea", "butcher", "chimneycakes", "churros", "cideries", "coffee&tea", "coffee&teasupplies", "coffeeroasteries", "conveniencestores", "csa", "cupcakes", "customcakes", "delicatessen", "desserts", "distilleries", "do-it-yourselffood", "donairs", "donuts", "empanadas", "ethicalgrocery", "farmersmarket", "fishmonger", "fooddeliveryservices", "foodtrucks", "friterie", "gelato", "grocery", "hawkercentre", "honey", "icecream&frozenyogurt", "importedfood", "internationalgrocery", "internetcafes", "japanesesweets", "taiyaki", "juicebars&smoothies", "kiosk", "kombucha", "meaderies", "milkshakebars", "mulledwine", "nasilemak", "organicstores", "panzerotti", "parentcafes", "patisserie/cakeshop", "piadina", "poke", "pretzels", "salumerie", "shavedice", "shavedsnow", "smokehouse", "specialtyfood", "candystores", "cheeseshops", "chocolatiers&shops", "dagashi", "driedfruit", "frozenfood", "fruits&veggies", "healthmarkets", "herbs&spices", "macarons", "meatshops", "pastashops", "popcornshops", "seafoodmarkets", "tofushops", "streetvendors", "sugarshacks", "tearooms", "torshi", "tortillas", "waterstores", "wineries", "zapiekanka", "adultentertainment", "stripclubs", "stripteasedancers", "barcrawl", "bars", "beerbar", "champagnebars", "cigarbars", "cocktailbars", "divebars", "drive-thrubars", "gaybars", "hookahbars", "irishpub", "lounges", "pubs", "speakeasies", "sportsbars", "tikibars", "vermouthbars", "whiskeybars", "winebars", "beergardens", "clubcrawl", "comedyclubs", "countrydancehalls", "danceclubs", "jazz&blues", "karaoke", "musicvenues", "pianobars", "poolhalls","afghan", "african", "senegalese", "southafrican", "american(new)", "american(traditional)", "andalusian", "arabian", "arabpizza", "argentine", "armenian", "asianfusion", "asturian", "australian", "austrian", "baguettes", "bangladeshi", "barbeque", "basque", "bavarian", "beergarden", "beerhall", "beisl", "belgian", "flemish", "bistros", "blacksea", "brasseries", "brazilian", "brazilianempanadas", "centralbrazilian", "northeasternbrazilian", "northernbrazilian", "rodizios", "breakfast&brunch", "pancakes", "british", "buffets", "bulgarian", "burgers", "burmese", "cafes", "themedcafes", "cafeteria", "cajun/creole", "cambodian", "canadian(new)", "canteen", "caribbean", "dominican", "haitian", "puertorican", "trinidadian", "catalan", "cheesesteaks", "chickenshop", "chickenwings", "chilean", "chinese", "cantonese", "congee", "dimsum", "fuzhou", "hainan", "hakka", "henghwa", "hokkien", "hunan", "pekinese", "shanghainese", "szechuan", "teochew", "comfortfood", "corsican", "creperies", "cuban", "currysausage", "cypriot", "czech", "czech/slovakian", "danish", "delis", "diners", "dinnertheater", "dumplings", "easterneuropean", "eritrean", "ethiopian", "fastfood", "filipino", "fischbroetchen", "fish&chips", "flatbread", "fondue", "foodcourt", "foodstands", "freiduria", "french", "alsatian", "auvergnat", "berrichon", "bourguignon", "mauritius", "nicoise", "provencal", "frenchsouthwest", "galician", "gamemeat", "gastropubs", "georgian", "german", "baden", "easterngerman", "franconian", "hessian", "northerngerman", "palatine", "rhinelandian", "giblets", "gluten-free", "greek", "guamanian", "halal", "hawaiian", "heuriger", "himalayan/nepalese", "honduran", "hongkongstylecafe", "hotdogs", "hotpot", "hungarian", "iberian", "indian", "indonesian", "international", "irish", "islandpub", "israeli", "italian", "abruzzese", "altoatesine", "apulian", "calabrian", "cucinacampana", "emilian", "friulan", "ligurian", "lumbard", "napoletana", "piemonte", "roman", "sardinian", "sicilian", "tuscan", "venetian", "japanese", "blowfish", "conveyorbeltushi", "donburi", "gyudon", "oyakodon", "handrolls", "horumon", "izakaya", "japanesecurry", "kaiseki", "kushikatsu", "oden", "okinawan", "okonomiyaki", "onigiri", "ramen", "robatayaki", "soba", "sukiyaki", "takoyaki", "tempura", "teppanyaki", "tonkatsu", "udon", "unagi", "westernstylejapanesefood", "yakiniku", "yakitori", "jewish", "kebab", "kopitiam", "korean", "kosher", "kurdish", "laos", "laotian", "latinamerican", "colombian", "salvadoran", "venezuelan", "live/rawfood", "lyonnais", "malaysian", "mamak", "nyonya", "meatballs", "mediterranean", "falafel", "mexican", "easternmexican", "jaliscan", "northernmexican", "oaxacan", "pueblan", "tacos", "tamales", "yucatan", "middleeastern", "egyptian", "lebanese", "milkbars", "modernaustralian", "moderneuropean", "mongolian", "moroccan", "newmexicancuisine", "newzealand", "nicaraguan", "nightfood", "nikkei", "noodles", "norcinerie", "opensandwiches", "oriental", "pakistani", "panasian", "parentcafes", "parma", "persian/iranian", "peruvian", "pf/comercial", "pita", "pizza", "polish", "pierogis", "polynesian", "pop-uprestaurants", "portuguese", "alentejo", "algarve", "azores", "beira", "fadohouses", "madeira", "minho", "ribatejo", "tras-os-montes", "potatoes", "poutineries", "pubfood", "rice", "romanian", "rotisseriechicken", "russian", "salad", "sandwiches", "scandinavian", "schnitzel", "scottish", "seafood", "serbocroatian", "signaturecuisine", "singaporean", "slovakian", "somali", "soulfood", "soup", "southern", "spanish", "arroceria/paella", "srilankan", "steakhouses", "supperclubs", "sushibars", "swabian", "swedish", "swissfood", "syrian", "tabernas", "taiwanese", "tapasbars", "tapas/smallplates", "tavolacalda", "tex-mex", "thai", "traditionalnorwegian", "traditionalwedish", "trattorie", "turkish", "cheeku", "gozleme", "lahmacun", "ottomancuisine", "turkishravioli", "ukrainian", "uzbek", "vegan", "vegetarian", "venison", "vietnamese", "waffles", "wok", "wraps", "yugoslav","parklets", "publicart", "unofficialyelpevents", "yelpevents"]
}
